// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: wello-fiat-hub/admin/v1/admin.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on WebhookEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WebhookEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WebhookEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WebhookEventMultiError, or
// nil if none found.
func (m *WebhookEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *WebhookEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Source

	// no validation rules for SourceId

	// no validation rules for Headers

	// no validation rules for Body

	// no validation rules for ContentType

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WebhookEventValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WebhookEventValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WebhookEventValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WebhookEventValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WebhookEventValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WebhookEventValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WebhookEventMultiError(errors)
	}

	return nil
}

// WebhookEventMultiError is an error wrapping multiple validation errors
// returned by WebhookEvent.ValidateAll() if the designated constraints aren't met.
type WebhookEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WebhookEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WebhookEventMultiError) AllErrors() []error { return m }

// WebhookEventValidationError is the validation error returned by
// WebhookEvent.Validate if the designated constraints aren't met.
type WebhookEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebhookEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebhookEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebhookEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebhookEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebhookEventValidationError) ErrorName() string { return "WebhookEventValidationError" }

// Error satisfies the builtin error interface
func (e WebhookEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebhookEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebhookEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebhookEventValidationError{}

// Validate checks the field values on GetWebhookEventsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWebhookEventsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWebhookEventsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWebhookEventsReqMultiError, or nil if none found.
func (m *GetWebhookEventsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWebhookEventsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPaging()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWebhookEventsReqValidationError{
					field:  "Paging",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWebhookEventsReqValidationError{
					field:  "Paging",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPaging()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWebhookEventsReqValidationError{
				field:  "Paging",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetFilters() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetWebhookEventsReqValidationError{
						field:  fmt.Sprintf("Filters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetWebhookEventsReqValidationError{
						field:  fmt.Sprintf("Filters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWebhookEventsReqValidationError{
					field:  fmt.Sprintf("Filters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetOrderBy() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetWebhookEventsReqValidationError{
						field:  fmt.Sprintf("OrderBy[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetWebhookEventsReqValidationError{
						field:  fmt.Sprintf("OrderBy[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWebhookEventsReqValidationError{
					field:  fmt.Sprintf("OrderBy[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetWebhookEventsReqMultiError(errors)
	}

	return nil
}

// GetWebhookEventsReqMultiError is an error wrapping multiple validation
// errors returned by GetWebhookEventsReq.ValidateAll() if the designated
// constraints aren't met.
type GetWebhookEventsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWebhookEventsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWebhookEventsReqMultiError) AllErrors() []error { return m }

// GetWebhookEventsReqValidationError is the validation error returned by
// GetWebhookEventsReq.Validate if the designated constraints aren't met.
type GetWebhookEventsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWebhookEventsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWebhookEventsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWebhookEventsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWebhookEventsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWebhookEventsReqValidationError) ErrorName() string {
	return "GetWebhookEventsReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetWebhookEventsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWebhookEventsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWebhookEventsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWebhookEventsReqValidationError{}

// Validate checks the field values on GetWebhookEventsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWebhookEventsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWebhookEventsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWebhookEventsReplyMultiError, or nil if none found.
func (m *GetWebhookEventsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWebhookEventsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	// no validation rules for Skip

	// no validation rules for Limit

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetWebhookEventsReplyValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetWebhookEventsReplyValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWebhookEventsReplyValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetWebhookEventsReplyMultiError(errors)
	}

	return nil
}

// GetWebhookEventsReplyMultiError is an error wrapping multiple validation
// errors returned by GetWebhookEventsReply.ValidateAll() if the designated
// constraints aren't met.
type GetWebhookEventsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWebhookEventsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWebhookEventsReplyMultiError) AllErrors() []error { return m }

// GetWebhookEventsReplyValidationError is the validation error returned by
// GetWebhookEventsReply.Validate if the designated constraints aren't met.
type GetWebhookEventsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWebhookEventsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWebhookEventsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWebhookEventsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWebhookEventsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWebhookEventsReplyValidationError) ErrorName() string {
	return "GetWebhookEventsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetWebhookEventsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWebhookEventsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWebhookEventsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWebhookEventsReplyValidationError{}

// Validate checks the field values on GetTransactionStatusLogsReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionStatusLogsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionStatusLogsReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionStatusLogsReqMultiError, or nil if none found.
func (m *GetTransactionStatusLogsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionStatusLogsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetTransactionStatusLogsReqMultiError(errors)
	}

	return nil
}

// GetTransactionStatusLogsReqMultiError is an error wrapping multiple
// validation errors returned by GetTransactionStatusLogsReq.ValidateAll() if
// the designated constraints aren't met.
type GetTransactionStatusLogsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionStatusLogsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionStatusLogsReqMultiError) AllErrors() []error { return m }

// GetTransactionStatusLogsReqValidationError is the validation error returned
// by GetTransactionStatusLogsReq.Validate if the designated constraints
// aren't met.
type GetTransactionStatusLogsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionStatusLogsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionStatusLogsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionStatusLogsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionStatusLogsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionStatusLogsReqValidationError) ErrorName() string {
	return "GetTransactionStatusLogsReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionStatusLogsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionStatusLogsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionStatusLogsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionStatusLogsReqValidationError{}

// Validate checks the field values on TransactionStatusLog with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TransactionStatusLog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionStatusLog with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionStatusLogMultiError, or nil if none found.
func (m *TransactionStatusLog) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionStatusLog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TransactionId

	// no validation rules for FromStatus

	// no validation rules for ToStatus

	// no validation rules for FromStatusCode

	// no validation rules for ToStatusCode

	// no validation rules for FromChannelStatus

	// no validation rules for ToChannelStatus

	// no validation rules for FromChannelMessage

	// no validation rules for ToChannelMessage

	// no validation rules for Note

	// no validation rules for UpdatedBy

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionStatusLogValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionStatusLogValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionStatusLogValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionStatusLogValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionStatusLogValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionStatusLogValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TransactionStatusLogMultiError(errors)
	}

	return nil
}

// TransactionStatusLogMultiError is an error wrapping multiple validation
// errors returned by TransactionStatusLog.ValidateAll() if the designated
// constraints aren't met.
type TransactionStatusLogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionStatusLogMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionStatusLogMultiError) AllErrors() []error { return m }

// TransactionStatusLogValidationError is the validation error returned by
// TransactionStatusLog.Validate if the designated constraints aren't met.
type TransactionStatusLogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionStatusLogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionStatusLogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionStatusLogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionStatusLogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionStatusLogValidationError) ErrorName() string {
	return "TransactionStatusLogValidationError"
}

// Error satisfies the builtin error interface
func (e TransactionStatusLogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionStatusLog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionStatusLogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionStatusLogValidationError{}

// Validate checks the field values on GetTransactionStatusLogsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionStatusLogsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionStatusLogsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetTransactionStatusLogsReplyMultiError, or nil if none found.
func (m *GetTransactionStatusLogsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionStatusLogsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLogs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTransactionStatusLogsReplyValidationError{
						field:  fmt.Sprintf("Logs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTransactionStatusLogsReplyValidationError{
						field:  fmt.Sprintf("Logs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTransactionStatusLogsReplyValidationError{
					field:  fmt.Sprintf("Logs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetTransactionStatusLogsReplyMultiError(errors)
	}

	return nil
}

// GetTransactionStatusLogsReplyMultiError is an error wrapping multiple
// validation errors returned by GetTransactionStatusLogsReply.ValidateAll()
// if the designated constraints aren't met.
type GetTransactionStatusLogsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionStatusLogsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionStatusLogsReplyMultiError) AllErrors() []error { return m }

// GetTransactionStatusLogsReplyValidationError is the validation error
// returned by GetTransactionStatusLogsReply.Validate if the designated
// constraints aren't met.
type GetTransactionStatusLogsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionStatusLogsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionStatusLogsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionStatusLogsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionStatusLogsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionStatusLogsReplyValidationError) ErrorName() string {
	return "GetTransactionStatusLogsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionStatusLogsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionStatusLogsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionStatusLogsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionStatusLogsReplyValidationError{}

// Validate checks the field values on MigrateCardTempReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MigrateCardTempReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MigrateCardTempReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MigrateCardTempReqMultiError, or nil if none found.
func (m *MigrateCardTempReq) ValidateAll() error {
	return m.validate(true)
}

func (m *MigrateCardTempReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.DryRun != nil {
		// no validation rules for DryRun
	}

	if len(errors) > 0 {
		return MigrateCardTempReqMultiError(errors)
	}

	return nil
}

// MigrateCardTempReqMultiError is an error wrapping multiple validation errors
// returned by MigrateCardTempReq.ValidateAll() if the designated constraints
// aren't met.
type MigrateCardTempReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MigrateCardTempReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MigrateCardTempReqMultiError) AllErrors() []error { return m }

// MigrateCardTempReqValidationError is the validation error returned by
// MigrateCardTempReq.Validate if the designated constraints aren't met.
type MigrateCardTempReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MigrateCardTempReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MigrateCardTempReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MigrateCardTempReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MigrateCardTempReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MigrateCardTempReqValidationError) ErrorName() string {
	return "MigrateCardTempReqValidationError"
}

// Error satisfies the builtin error interface
func (e MigrateCardTempReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMigrateCardTempReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MigrateCardTempReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MigrateCardTempReqValidationError{}

// Validate checks the field values on MigrateCardTempReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MigrateCardTempReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MigrateCardTempReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MigrateCardTempReplyMultiError, or nil if none found.
func (m *MigrateCardTempReply) ValidateAll() error {
	return m.validate(true)
}

func (m *MigrateCardTempReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return MigrateCardTempReplyMultiError(errors)
	}

	return nil
}

// MigrateCardTempReplyMultiError is an error wrapping multiple validation
// errors returned by MigrateCardTempReply.ValidateAll() if the designated
// constraints aren't met.
type MigrateCardTempReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MigrateCardTempReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MigrateCardTempReplyMultiError) AllErrors() []error { return m }

// MigrateCardTempReplyValidationError is the validation error returned by
// MigrateCardTempReply.Validate if the designated constraints aren't met.
type MigrateCardTempReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MigrateCardTempReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MigrateCardTempReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MigrateCardTempReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MigrateCardTempReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MigrateCardTempReplyValidationError) ErrorName() string {
	return "MigrateCardTempReplyValidationError"
}

// Error satisfies the builtin error interface
func (e MigrateCardTempReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMigrateCardTempReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MigrateCardTempReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MigrateCardTempReplyValidationError{}

// Validate checks the field values on ReplayWebhookEventReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplayWebhookEventReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayWebhookEventReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReplayWebhookEventReqMultiError, or nil if none found.
func (m *ReplayWebhookEventReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayWebhookEventReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !strings.HasPrefix(m.GetWebhookEventId(), "wh_") {
		err := ReplayWebhookEventReqValidationError{
			field:  "WebhookEventId",
			reason: "value does not have prefix \"wh_\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Forward != nil {
		// no validation rules for Forward
	}

	if len(errors) > 0 {
		return ReplayWebhookEventReqMultiError(errors)
	}

	return nil
}

// ReplayWebhookEventReqMultiError is an error wrapping multiple validation
// errors returned by ReplayWebhookEventReq.ValidateAll() if the designated
// constraints aren't met.
type ReplayWebhookEventReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayWebhookEventReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayWebhookEventReqMultiError) AllErrors() []error { return m }

// ReplayWebhookEventReqValidationError is the validation error returned by
// ReplayWebhookEventReq.Validate if the designated constraints aren't met.
type ReplayWebhookEventReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayWebhookEventReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayWebhookEventReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayWebhookEventReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayWebhookEventReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayWebhookEventReqValidationError) ErrorName() string {
	return "ReplayWebhookEventReqValidationError"
}

// Error satisfies the builtin error interface
func (e ReplayWebhookEventReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayWebhookEventReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayWebhookEventReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayWebhookEventReqValidationError{}

// Validate checks the field values on ReplayWebhookEventReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplayWebhookEventReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayWebhookEventReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReplayWebhookEventReplyMultiError, or nil if none found.
func (m *ReplayWebhookEventReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayWebhookEventReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NewWebhookEventId

	// no validation rules for OriginalWebhookEventId

	// no validation rules for ForwardCount

	if len(errors) > 0 {
		return ReplayWebhookEventReplyMultiError(errors)
	}

	return nil
}

// ReplayWebhookEventReplyMultiError is an error wrapping multiple validation
// errors returned by ReplayWebhookEventReply.ValidateAll() if the designated
// constraints aren't met.
type ReplayWebhookEventReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayWebhookEventReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayWebhookEventReplyMultiError) AllErrors() []error { return m }

// ReplayWebhookEventReplyValidationError is the validation error returned by
// ReplayWebhookEventReply.Validate if the designated constraints aren't met.
type ReplayWebhookEventReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayWebhookEventReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayWebhookEventReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayWebhookEventReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayWebhookEventReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayWebhookEventReplyValidationError) ErrorName() string {
	return "ReplayWebhookEventReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ReplayWebhookEventReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayWebhookEventReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayWebhookEventReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayWebhookEventReplyValidationError{}

// Validate checks the field values on ReplayTransactionStatusEventReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplayTransactionStatusEventReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayTransactionStatusEventReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ReplayTransactionStatusEventReqMultiError, or nil if none found.
func (m *ReplayTransactionStatusEventReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayTransactionStatusEventReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.TransactionId != nil {

		if !_ReplayTransactionStatusEventReq_TransactionId_Pattern.MatchString(m.GetTransactionId()) {
			err := ReplayTransactionStatusEventReqValidationError{
				field:  "TransactionId",
				reason: "value does not match regex pattern \"^(pi_|po_).*$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ReplayTransactionStatusEventReqMultiError(errors)
	}

	return nil
}

// ReplayTransactionStatusEventReqMultiError is an error wrapping multiple
// validation errors returned by ReplayTransactionStatusEventReq.ValidateAll()
// if the designated constraints aren't met.
type ReplayTransactionStatusEventReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayTransactionStatusEventReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayTransactionStatusEventReqMultiError) AllErrors() []error { return m }

// ReplayTransactionStatusEventReqValidationError is the validation error
// returned by ReplayTransactionStatusEventReq.Validate if the designated
// constraints aren't met.
type ReplayTransactionStatusEventReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayTransactionStatusEventReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayTransactionStatusEventReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayTransactionStatusEventReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayTransactionStatusEventReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayTransactionStatusEventReqValidationError) ErrorName() string {
	return "ReplayTransactionStatusEventReqValidationError"
}

// Error satisfies the builtin error interface
func (e ReplayTransactionStatusEventReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayTransactionStatusEventReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayTransactionStatusEventReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayTransactionStatusEventReqValidationError{}

var _ReplayTransactionStatusEventReq_TransactionId_Pattern = regexp.MustCompile("^(pi_|po_).*$")

// Validate checks the field values on ReplayTransactionStatusEventReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ReplayTransactionStatusEventReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplayTransactionStatusEventReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ReplayTransactionStatusEventReplyMultiError, or nil if none found.
func (m *ReplayTransactionStatusEventReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplayTransactionStatusEventReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return ReplayTransactionStatusEventReplyMultiError(errors)
	}

	return nil
}

// ReplayTransactionStatusEventReplyMultiError is an error wrapping multiple
// validation errors returned by
// ReplayTransactionStatusEventReply.ValidateAll() if the designated
// constraints aren't met.
type ReplayTransactionStatusEventReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplayTransactionStatusEventReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplayTransactionStatusEventReplyMultiError) AllErrors() []error { return m }

// ReplayTransactionStatusEventReplyValidationError is the validation error
// returned by ReplayTransactionStatusEventReply.Validate if the designated
// constraints aren't met.
type ReplayTransactionStatusEventReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplayTransactionStatusEventReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplayTransactionStatusEventReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplayTransactionStatusEventReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplayTransactionStatusEventReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplayTransactionStatusEventReplyValidationError) ErrorName() string {
	return "ReplayTransactionStatusEventReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ReplayTransactionStatusEventReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplayTransactionStatusEventReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplayTransactionStatusEventReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplayTransactionStatusEventReplyValidationError{}

// Validate checks the field values on UpdateCardCardMetaReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCardCardMetaReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCardCardMetaReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCardCardMetaReqMultiError, or nil if none found.
func (m *UpdateCardCardMetaReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCardCardMetaReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !strings.HasPrefix(m.GetCardId(), "card_") {
		err := UpdateCardCardMetaReqValidationError{
			field:  "CardId",
			reason: "value does not have prefix \"card_\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ChannelId

	if len(errors) > 0 {
		return UpdateCardCardMetaReqMultiError(errors)
	}

	return nil
}

// UpdateCardCardMetaReqMultiError is an error wrapping multiple validation
// errors returned by UpdateCardCardMetaReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateCardCardMetaReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCardCardMetaReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCardCardMetaReqMultiError) AllErrors() []error { return m }

// UpdateCardCardMetaReqValidationError is the validation error returned by
// UpdateCardCardMetaReq.Validate if the designated constraints aren't met.
type UpdateCardCardMetaReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCardCardMetaReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCardCardMetaReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCardCardMetaReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCardCardMetaReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCardCardMetaReqValidationError) ErrorName() string {
	return "UpdateCardCardMetaReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCardCardMetaReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCardCardMetaReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCardCardMetaReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCardCardMetaReqValidationError{}

// Validate checks the field values on UpdateCardCardMetaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCardCardMetaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCardCardMetaReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCardCardMetaReplyMultiError, or nil if none found.
func (m *UpdateCardCardMetaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCardCardMetaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !strings.HasPrefix(m.GetCardId(), "card_") {
		err := UpdateCardCardMetaReplyValidationError{
			field:  "CardId",
			reason: "value does not have prefix \"card_\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCard()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateCardCardMetaReplyValidationError{
					field:  "Card",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateCardCardMetaReplyValidationError{
					field:  "Card",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCard()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateCardCardMetaReplyValidationError{
				field:  "Card",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStats()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateCardCardMetaReplyValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateCardCardMetaReplyValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStats()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateCardCardMetaReplyValidationError{
				field:  "Stats",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateCardCardMetaReplyMultiError(errors)
	}

	return nil
}

// UpdateCardCardMetaReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateCardCardMetaReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateCardCardMetaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCardCardMetaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCardCardMetaReplyMultiError) AllErrors() []error { return m }

// UpdateCardCardMetaReplyValidationError is the validation error returned by
// UpdateCardCardMetaReply.Validate if the designated constraints aren't met.
type UpdateCardCardMetaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCardCardMetaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCardCardMetaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCardCardMetaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCardCardMetaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCardCardMetaReplyValidationError) ErrorName() string {
	return "UpdateCardCardMetaReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCardCardMetaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCardCardMetaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCardCardMetaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCardCardMetaReplyValidationError{}
