// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: wello-account/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_SignFlowCreate_FullMethodName         = "/user.service.v1.User/SignFlowCreate"
	User_SignFlowSend_FullMethodName           = "/user.service.v1.User/SignFlowSend"
	User_SignFlowValidate_FullMethodName       = "/user.service.v1.User/SignFlowValidate"
	User_LoginByPassword_FullMethodName        = "/user.service.v1.User/LoginByPassword"
	User_CheckAccessToken_FullMethodName       = "/user.service.v1.User/CheckAccessToken"
	User_GetAccessToken_FullMethodName         = "/user.service.v1.User/GetAccessToken"
	User_GetUserInfo_FullMethodName            = "/user.service.v1.User/GetUserInfo"
	User_QueryUserInfo_FullMethodName          = "/user.service.v1.User/QueryUserInfo"
	User_GetUserMobile_FullMethodName          = "/user.service.v1.User/GetUserMobile"
	User_GetUserEmail_FullMethodName           = "/user.service.v1.User/GetUserEmail"
	User_CheckUsername_FullMethodName          = "/user.service.v1.User/CheckUsername"
	User_SetupUsername_FullMethodName          = "/user.service.v1.User/SetupUsername"
	User_SetupNickname_FullMethodName          = "/user.service.v1.User/SetupNickname"
	User_SetupDob_FullMethodName               = "/user.service.v1.User/SetupDob"
	User_SetupAvatar_FullMethodName            = "/user.service.v1.User/SetupAvatar"
	User_UpdateFiatCurrency_FullMethodName     = "/user.service.v1.User/UpdateFiatCurrency"
	User_UpdateNotificationOn_FullMethodName   = "/user.service.v1.User/UpdateNotificationOn"
	User_SetupPassword_FullMethodName          = "/user.service.v1.User/SetupPassword"
	User_BindEmailFlowCreate_FullMethodName    = "/user.service.v1.User/BindEmailFlowCreate"
	User_BindEmailFlowSend_FullMethodName      = "/user.service.v1.User/BindEmailFlowSend"
	User_BindEmailFlowValidate_FullMethodName  = "/user.service.v1.User/BindEmailFlowValidate"
	User_BindOAuthFlowCreate_FullMethodName    = "/user.service.v1.User/BindOAuthFlowCreate"
	User_BindOAuthFlowValidate_FullMethodName  = "/user.service.v1.User/BindOAuthFlowValidate"
	User_GetUserKycInfo_FullMethodName         = "/user.service.v1.User/GetUserKycInfo"
	User_GetUserKycDetailInfo_FullMethodName   = "/user.service.v1.User/GetUserKycDetailInfo"
	User_GetKycAccessToken_FullMethodName      = "/user.service.v1.User/GetKycAccessToken"
	User_UploadKycResult_FullMethodName        = "/user.service.v1.User/UploadKycResult"
	User_UpdateKycDetailPending_FullMethodName = "/user.service.v1.User/UpdateKycDetailPending"
	User_UpdateKycDetailAll_FullMethodName     = "/user.service.v1.User/UpdateKycDetailAll"
	User_Logout_FullMethodName                 = "/user.service.v1.User/Logout"
	User_CloseAccountPreCheck_FullMethodName   = "/user.service.v1.User/CloseAccountPreCheck"
	User_CloseAccount_FullMethodName           = "/user.service.v1.User/CloseAccount"
	User_GetUserLimits_FullMethodName          = "/user.service.v1.User/GetUserLimits"
	User_GetUserSavedWallets_FullMethodName    = "/user.service.v1.User/GetUserSavedWallets"
	User_UserAddSavedWallet_FullMethodName     = "/user.service.v1.User/UserAddSavedWallet"
	User_UserDeleteSavedWallet_FullMethodName  = "/user.service.v1.User/UserDeleteSavedWallet"
	User_UserUpdateSavedWallet_FullMethodName  = "/user.service.v1.User/UserUpdateSavedWallet"
	User_BindInviter_FullMethodName            = "/user.service.v1.User/BindInviter"
	User_GetSupportCountries_FullMethodName    = "/user.service.v1.User/GetSupportCountries"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// 注册登录流程第一步(主要是选择登录注册的方式)
	SignFlowCreate(ctx context.Context, in *SignFlowCreateReq, opts ...grpc.CallOption) (*SignFlowCreateResp, error)
	// 注册登录流程第一步(发送对应的验证码SMS/Email)
	SignFlowSend(ctx context.Context, in *SignFlowSendReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 注册登录流程第三步(验证验证码&登录注册账号)
	SignFlowValidate(ctx context.Context, in *SignFlowValidateReq, opts ...grpc.CallOption) (*SignFlowValidateResp, error)
	// Login
	LoginByPassword(ctx context.Context, in *LoginByPasswordReq, opts ...grpc.CallOption) (*LoginByPasswordResp, error)
	// 检查是否登录
	CheckAccessToken(ctx context.Context, in *CheckAccessTokenReq, opts ...grpc.CallOption) (*CheckAccessTokenReply, error)
	// 刷新登录Token时长
	GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenReply, error)
	// 获取用户简单信息
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	// 批量查询指定用户信息
	QueryUserInfo(ctx context.Context, in *QueryUserInfoReq, opts ...grpc.CallOption) (*QueryUserInfoReply, error)
	// 获取用户手机号
	GetUserMobile(ctx context.Context, in *GetUserMobileReq, opts ...grpc.CallOption) (*GetUserMobileReply, error)
	// 获取用户邮箱
	GetUserEmail(ctx context.Context, in *GetUserEmailReq, opts ...grpc.CallOption) (*GetUserEmailReply, error)
	// 检查Username是否存在
	CheckUsername(ctx context.Context, in *CheckUsernameReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 设置Username
	SetupUsername(ctx context.Context, in *SetupUsernameReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 设置昵称
	SetupNickname(ctx context.Context, in *SetupNicknameReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 设置DOB
	SetupDob(ctx context.Context, in *SetupDobReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 设置头像
	SetupAvatar(ctx context.Context, in *SetupAvatarReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新FiatCurrency
	UpdateFiatCurrency(ctx context.Context, in *UpdateFiatCurrencyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新NotificationOn
	UpdateNotificationOn(ctx context.Context, in *UpdateNotificationOnReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 设置账号密码(旧密码)
	SetupPassword(ctx context.Context, in *SetupPasswordReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 绑定邮箱第一步(创建Flow)
	BindEmailFlowCreate(ctx context.Context, in *BindEmailFlowCreateReq, opts ...grpc.CallOption) (*BindEmailFlowCreateReply, error)
	// 绑定邮箱第二步(发送邮箱验证码)
	BindEmailFlowSend(ctx context.Context, in *BindEmailFlowSendReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 绑定邮箱第三步(验证验证码)
	BindEmailFlowValidate(ctx context.Context, in *BindEmailFlowValidateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 绑定OAuth第一步(创建Flow)
	BindOAuthFlowCreate(ctx context.Context, in *BindOAuthFlowCreateReq, opts ...grpc.CallOption) (*BindOAuthFlowCreateReply, error)
	// 绑定OAuth第二步(验证Token并绑定)
	BindOAuthFlowValidate(ctx context.Context, in *BindOAuthFlowValidateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取用户KYC简单信息
	GetUserKycInfo(ctx context.Context, in *GetUserKycInfoReq, opts ...grpc.CallOption) (*GetUserKycInfoReply, error)
	// 获取用户KYC详细信息
	GetUserKycDetailInfo(ctx context.Context, in *GetUserKycDetailInfoReq, opts ...grpc.CallOption) (*GetUserKycDetailInfoReply, error)
	// 获取KYC初始化用的AccessToken
	GetKycAccessToken(ctx context.Context, in *GetKycAccessTokenReq, opts ...grpc.CallOption) (*GetKycAccessTokenReply, error)
	// 上传KYC结果
	UploadKycResult(ctx context.Context, in *UploadKycResultReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新用户KYC信息(Task用)
	UpdateKycDetailPending(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateKycDetailAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 退出登录
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 注销账户预检查
	CloseAccountPreCheck(ctx context.Context, in *CloseAccountPreCheckReq, opts ...grpc.CallOption) (*CloseAccountPreCheckResp, error)
	// 注销账户
	CloseAccount(ctx context.Context, in *CloseAccountReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取用户的UserLimits
	GetUserLimits(ctx context.Context, in *GetUserLimitsReq, opts ...grpc.CallOption) (*GetUserLimitsResp, error)
	// 获取用户SavedWallet列表
	GetUserSavedWallets(ctx context.Context, in *GetUserSavedWalletsReq, opts ...grpc.CallOption) (*GetUserSavedWalletsResp, error)
	// 用户新增SavedWallet
	UserAddSavedWallet(ctx context.Context, in *UserAddSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 用户删除SavedWallet
	UserDeleteSavedWallet(ctx context.Context, in *UserDeleteSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 用户编辑SavedWallet
	UserUpdateSavedWallet(ctx context.Context, in *UserUpdateSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 绑定邀请人
	BindInviter(ctx context.Context, in *BindInviterReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取支持的国家和手机区号
	GetSupportCountries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportCountriesResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) SignFlowCreate(ctx context.Context, in *SignFlowCreateReq, opts ...grpc.CallOption) (*SignFlowCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignFlowCreateResp)
	err := c.cc.Invoke(ctx, User_SignFlowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SignFlowSend(ctx context.Context, in *SignFlowSendReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SignFlowSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SignFlowValidate(ctx context.Context, in *SignFlowValidateReq, opts ...grpc.CallOption) (*SignFlowValidateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignFlowValidateResp)
	err := c.cc.Invoke(ctx, User_SignFlowValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LoginByPassword(ctx context.Context, in *LoginByPasswordReq, opts ...grpc.CallOption) (*LoginByPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginByPasswordResp)
	err := c.cc.Invoke(ctx, User_LoginByPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CheckAccessToken(ctx context.Context, in *CheckAccessTokenReq, opts ...grpc.CallOption) (*CheckAccessTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessTokenReply)
	err := c.cc.Invoke(ctx, User_CheckAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessTokenReply)
	err := c.cc.Invoke(ctx, User_GetAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoReply)
	err := c.cc.Invoke(ctx, User_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) QueryUserInfo(ctx context.Context, in *QueryUserInfoReq, opts ...grpc.CallOption) (*QueryUserInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserInfoReply)
	err := c.cc.Invoke(ctx, User_QueryUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserMobile(ctx context.Context, in *GetUserMobileReq, opts ...grpc.CallOption) (*GetUserMobileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMobileReply)
	err := c.cc.Invoke(ctx, User_GetUserMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserEmail(ctx context.Context, in *GetUserEmailReq, opts ...grpc.CallOption) (*GetUserEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEmailReply)
	err := c.cc.Invoke(ctx, User_GetUserEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CheckUsername(ctx context.Context, in *CheckUsernameReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_CheckUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetupUsername(ctx context.Context, in *SetupUsernameReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SetupUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetupNickname(ctx context.Context, in *SetupNicknameReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SetupNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetupDob(ctx context.Context, in *SetupDobReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SetupDob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetupAvatar(ctx context.Context, in *SetupAvatarReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SetupAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateFiatCurrency(ctx context.Context, in *UpdateFiatCurrencyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UpdateFiatCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateNotificationOn(ctx context.Context, in *UpdateNotificationOnReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UpdateNotificationOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetupPassword(ctx context.Context, in *SetupPasswordReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_SetupPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindEmailFlowCreate(ctx context.Context, in *BindEmailFlowCreateReq, opts ...grpc.CallOption) (*BindEmailFlowCreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindEmailFlowCreateReply)
	err := c.cc.Invoke(ctx, User_BindEmailFlowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindEmailFlowSend(ctx context.Context, in *BindEmailFlowSendReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_BindEmailFlowSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindEmailFlowValidate(ctx context.Context, in *BindEmailFlowValidateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_BindEmailFlowValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindOAuthFlowCreate(ctx context.Context, in *BindOAuthFlowCreateReq, opts ...grpc.CallOption) (*BindOAuthFlowCreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindOAuthFlowCreateReply)
	err := c.cc.Invoke(ctx, User_BindOAuthFlowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindOAuthFlowValidate(ctx context.Context, in *BindOAuthFlowValidateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_BindOAuthFlowValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserKycInfo(ctx context.Context, in *GetUserKycInfoReq, opts ...grpc.CallOption) (*GetUserKycInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserKycInfoReply)
	err := c.cc.Invoke(ctx, User_GetUserKycInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserKycDetailInfo(ctx context.Context, in *GetUserKycDetailInfoReq, opts ...grpc.CallOption) (*GetUserKycDetailInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserKycDetailInfoReply)
	err := c.cc.Invoke(ctx, User_GetUserKycDetailInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetKycAccessToken(ctx context.Context, in *GetKycAccessTokenReq, opts ...grpc.CallOption) (*GetKycAccessTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKycAccessTokenReply)
	err := c.cc.Invoke(ctx, User_GetKycAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UploadKycResult(ctx context.Context, in *UploadKycResultReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UploadKycResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateKycDetailPending(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UpdateKycDetailPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateKycDetailAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UpdateKycDetailAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CloseAccountPreCheck(ctx context.Context, in *CloseAccountPreCheckReq, opts ...grpc.CallOption) (*CloseAccountPreCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAccountPreCheckResp)
	err := c.cc.Invoke(ctx, User_CloseAccountPreCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CloseAccount(ctx context.Context, in *CloseAccountReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_CloseAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserLimits(ctx context.Context, in *GetUserLimitsReq, opts ...grpc.CallOption) (*GetUserLimitsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLimitsResp)
	err := c.cc.Invoke(ctx, User_GetUserLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserSavedWallets(ctx context.Context, in *GetUserSavedWalletsReq, opts ...grpc.CallOption) (*GetUserSavedWalletsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSavedWalletsResp)
	err := c.cc.Invoke(ctx, User_GetUserSavedWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserAddSavedWallet(ctx context.Context, in *UserAddSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UserAddSavedWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserDeleteSavedWallet(ctx context.Context, in *UserDeleteSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UserDeleteSavedWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserUpdateSavedWallet(ctx context.Context, in *UserUpdateSavedWalletReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UserUpdateSavedWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) BindInviter(ctx context.Context, in *BindInviterReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_BindInviter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSupportCountries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportCountriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportCountriesResp)
	err := c.cc.Invoke(ctx, User_GetSupportCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	// 注册登录流程第一步(主要是选择登录注册的方式)
	SignFlowCreate(context.Context, *SignFlowCreateReq) (*SignFlowCreateResp, error)
	// 注册登录流程第一步(发送对应的验证码SMS/Email)
	SignFlowSend(context.Context, *SignFlowSendReq) (*emptypb.Empty, error)
	// 注册登录流程第三步(验证验证码&登录注册账号)
	SignFlowValidate(context.Context, *SignFlowValidateReq) (*SignFlowValidateResp, error)
	// Login
	LoginByPassword(context.Context, *LoginByPasswordReq) (*LoginByPasswordResp, error)
	// 检查是否登录
	CheckAccessToken(context.Context, *CheckAccessTokenReq) (*CheckAccessTokenReply, error)
	// 刷新登录Token时长
	GetAccessToken(context.Context, *GetAccessTokenReq) (*GetAccessTokenReply, error)
	// 获取用户简单信息
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoReply, error)
	// 批量查询指定用户信息
	QueryUserInfo(context.Context, *QueryUserInfoReq) (*QueryUserInfoReply, error)
	// 获取用户手机号
	GetUserMobile(context.Context, *GetUserMobileReq) (*GetUserMobileReply, error)
	// 获取用户邮箱
	GetUserEmail(context.Context, *GetUserEmailReq) (*GetUserEmailReply, error)
	// 检查Username是否存在
	CheckUsername(context.Context, *CheckUsernameReq) (*emptypb.Empty, error)
	// 设置Username
	SetupUsername(context.Context, *SetupUsernameReq) (*emptypb.Empty, error)
	// 设置昵称
	SetupNickname(context.Context, *SetupNicknameReq) (*emptypb.Empty, error)
	// 设置DOB
	SetupDob(context.Context, *SetupDobReq) (*emptypb.Empty, error)
	// 设置头像
	SetupAvatar(context.Context, *SetupAvatarReq) (*emptypb.Empty, error)
	// 更新FiatCurrency
	UpdateFiatCurrency(context.Context, *UpdateFiatCurrencyReq) (*emptypb.Empty, error)
	// 更新NotificationOn
	UpdateNotificationOn(context.Context, *UpdateNotificationOnReq) (*emptypb.Empty, error)
	// 设置账号密码(旧密码)
	SetupPassword(context.Context, *SetupPasswordReq) (*emptypb.Empty, error)
	// 绑定邮箱第一步(创建Flow)
	BindEmailFlowCreate(context.Context, *BindEmailFlowCreateReq) (*BindEmailFlowCreateReply, error)
	// 绑定邮箱第二步(发送邮箱验证码)
	BindEmailFlowSend(context.Context, *BindEmailFlowSendReq) (*emptypb.Empty, error)
	// 绑定邮箱第三步(验证验证码)
	BindEmailFlowValidate(context.Context, *BindEmailFlowValidateReq) (*emptypb.Empty, error)
	// 绑定OAuth第一步(创建Flow)
	BindOAuthFlowCreate(context.Context, *BindOAuthFlowCreateReq) (*BindOAuthFlowCreateReply, error)
	// 绑定OAuth第二步(验证Token并绑定)
	BindOAuthFlowValidate(context.Context, *BindOAuthFlowValidateReq) (*emptypb.Empty, error)
	// 获取用户KYC简单信息
	GetUserKycInfo(context.Context, *GetUserKycInfoReq) (*GetUserKycInfoReply, error)
	// 获取用户KYC详细信息
	GetUserKycDetailInfo(context.Context, *GetUserKycDetailInfoReq) (*GetUserKycDetailInfoReply, error)
	// 获取KYC初始化用的AccessToken
	GetKycAccessToken(context.Context, *GetKycAccessTokenReq) (*GetKycAccessTokenReply, error)
	// 上传KYC结果
	UploadKycResult(context.Context, *UploadKycResultReq) (*emptypb.Empty, error)
	// 更新用户KYC信息(Task用)
	UpdateKycDetailPending(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	UpdateKycDetailAll(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// 退出登录
	Logout(context.Context, *LogoutReq) (*emptypb.Empty, error)
	// 注销账户预检查
	CloseAccountPreCheck(context.Context, *CloseAccountPreCheckReq) (*CloseAccountPreCheckResp, error)
	// 注销账户
	CloseAccount(context.Context, *CloseAccountReq) (*emptypb.Empty, error)
	// 获取用户的UserLimits
	GetUserLimits(context.Context, *GetUserLimitsReq) (*GetUserLimitsResp, error)
	// 获取用户SavedWallet列表
	GetUserSavedWallets(context.Context, *GetUserSavedWalletsReq) (*GetUserSavedWalletsResp, error)
	// 用户新增SavedWallet
	UserAddSavedWallet(context.Context, *UserAddSavedWalletReq) (*emptypb.Empty, error)
	// 用户删除SavedWallet
	UserDeleteSavedWallet(context.Context, *UserDeleteSavedWalletReq) (*emptypb.Empty, error)
	// 用户编辑SavedWallet
	UserUpdateSavedWallet(context.Context, *UserUpdateSavedWalletReq) (*emptypb.Empty, error)
	// 绑定邀请人
	BindInviter(context.Context, *BindInviterReq) (*emptypb.Empty, error)
	// 获取支持的国家和手机区号
	GetSupportCountries(context.Context, *emptypb.Empty) (*GetSupportCountriesResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) SignFlowCreate(context.Context, *SignFlowCreateReq) (*SignFlowCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignFlowCreate not implemented")
}
func (UnimplementedUserServer) SignFlowSend(context.Context, *SignFlowSendReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignFlowSend not implemented")
}
func (UnimplementedUserServer) SignFlowValidate(context.Context, *SignFlowValidateReq) (*SignFlowValidateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignFlowValidate not implemented")
}
func (UnimplementedUserServer) LoginByPassword(context.Context, *LoginByPasswordReq) (*LoginByPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginByPassword not implemented")
}
func (UnimplementedUserServer) CheckAccessToken(context.Context, *CheckAccessTokenReq) (*CheckAccessTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccessToken not implemented")
}
func (UnimplementedUserServer) GetAccessToken(context.Context, *GetAccessTokenReq) (*GetAccessTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}
func (UnimplementedUserServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServer) QueryUserInfo(context.Context, *QueryUserInfoReq) (*QueryUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserInfo not implemented")
}
func (UnimplementedUserServer) GetUserMobile(context.Context, *GetUserMobileReq) (*GetUserMobileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMobile not implemented")
}
func (UnimplementedUserServer) GetUserEmail(context.Context, *GetUserEmailReq) (*GetUserEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEmail not implemented")
}
func (UnimplementedUserServer) CheckUsername(context.Context, *CheckUsernameReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsername not implemented")
}
func (UnimplementedUserServer) SetupUsername(context.Context, *SetupUsernameReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupUsername not implemented")
}
func (UnimplementedUserServer) SetupNickname(context.Context, *SetupNicknameReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupNickname not implemented")
}
func (UnimplementedUserServer) SetupDob(context.Context, *SetupDobReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDob not implemented")
}
func (UnimplementedUserServer) SetupAvatar(context.Context, *SetupAvatarReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupAvatar not implemented")
}
func (UnimplementedUserServer) UpdateFiatCurrency(context.Context, *UpdateFiatCurrencyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFiatCurrency not implemented")
}
func (UnimplementedUserServer) UpdateNotificationOn(context.Context, *UpdateNotificationOnReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotificationOn not implemented")
}
func (UnimplementedUserServer) SetupPassword(context.Context, *SetupPasswordReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupPassword not implemented")
}
func (UnimplementedUserServer) BindEmailFlowCreate(context.Context, *BindEmailFlowCreateReq) (*BindEmailFlowCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindEmailFlowCreate not implemented")
}
func (UnimplementedUserServer) BindEmailFlowSend(context.Context, *BindEmailFlowSendReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindEmailFlowSend not implemented")
}
func (UnimplementedUserServer) BindEmailFlowValidate(context.Context, *BindEmailFlowValidateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindEmailFlowValidate not implemented")
}
func (UnimplementedUserServer) BindOAuthFlowCreate(context.Context, *BindOAuthFlowCreateReq) (*BindOAuthFlowCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindOAuthFlowCreate not implemented")
}
func (UnimplementedUserServer) BindOAuthFlowValidate(context.Context, *BindOAuthFlowValidateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindOAuthFlowValidate not implemented")
}
func (UnimplementedUserServer) GetUserKycInfo(context.Context, *GetUserKycInfoReq) (*GetUserKycInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserKycInfo not implemented")
}
func (UnimplementedUserServer) GetUserKycDetailInfo(context.Context, *GetUserKycDetailInfoReq) (*GetUserKycDetailInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserKycDetailInfo not implemented")
}
func (UnimplementedUserServer) GetKycAccessToken(context.Context, *GetKycAccessTokenReq) (*GetKycAccessTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKycAccessToken not implemented")
}
func (UnimplementedUserServer) UploadKycResult(context.Context, *UploadKycResultReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadKycResult not implemented")
}
func (UnimplementedUserServer) UpdateKycDetailPending(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKycDetailPending not implemented")
}
func (UnimplementedUserServer) UpdateKycDetailAll(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKycDetailAll not implemented")
}
func (UnimplementedUserServer) Logout(context.Context, *LogoutReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedUserServer) CloseAccountPreCheck(context.Context, *CloseAccountPreCheckReq) (*CloseAccountPreCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseAccountPreCheck not implemented")
}
func (UnimplementedUserServer) CloseAccount(context.Context, *CloseAccountReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseAccount not implemented")
}
func (UnimplementedUserServer) GetUserLimits(context.Context, *GetUserLimitsReq) (*GetUserLimitsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLimits not implemented")
}
func (UnimplementedUserServer) GetUserSavedWallets(context.Context, *GetUserSavedWalletsReq) (*GetUserSavedWalletsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSavedWallets not implemented")
}
func (UnimplementedUserServer) UserAddSavedWallet(context.Context, *UserAddSavedWalletReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAddSavedWallet not implemented")
}
func (UnimplementedUserServer) UserDeleteSavedWallet(context.Context, *UserDeleteSavedWalletReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDeleteSavedWallet not implemented")
}
func (UnimplementedUserServer) UserUpdateSavedWallet(context.Context, *UserUpdateSavedWalletReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateSavedWallet not implemented")
}
func (UnimplementedUserServer) BindInviter(context.Context, *BindInviterReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindInviter not implemented")
}
func (UnimplementedUserServer) GetSupportCountries(context.Context, *emptypb.Empty) (*GetSupportCountriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportCountries not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_SignFlowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignFlowCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SignFlowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SignFlowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SignFlowCreate(ctx, req.(*SignFlowCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SignFlowSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignFlowSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SignFlowSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SignFlowSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SignFlowSend(ctx, req.(*SignFlowSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SignFlowValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignFlowValidateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SignFlowValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SignFlowValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SignFlowValidate(ctx, req.(*SignFlowValidateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LoginByPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LoginByPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_LoginByPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LoginByPassword(ctx, req.(*LoginByPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CheckAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CheckAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckAccessToken(ctx, req.(*CheckAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAccessToken(ctx, req.(*GetAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_QueryUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).QueryUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_QueryUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).QueryUserInfo(ctx, req.(*QueryUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMobileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserMobile(ctx, req.(*GetUserMobileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserEmail(ctx, req.(*GetUserEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CheckUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckUsername(ctx, req.(*CheckUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetupUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetupUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetupUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetupUsername(ctx, req.(*SetupUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetupNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupNicknameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetupNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetupNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetupNickname(ctx, req.(*SetupNicknameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetupDob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupDobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetupDob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetupDob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetupDob(ctx, req.(*SetupDobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetupAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupAvatarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetupAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetupAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetupAvatar(ctx, req.(*SetupAvatarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateFiatCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFiatCurrencyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateFiatCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateFiatCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateFiatCurrency(ctx, req.(*UpdateFiatCurrencyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateNotificationOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationOnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateNotificationOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateNotificationOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateNotificationOn(ctx, req.(*UpdateNotificationOnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetupPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetupPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SetupPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetupPassword(ctx, req.(*SetupPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindEmailFlowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEmailFlowCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindEmailFlowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindEmailFlowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindEmailFlowCreate(ctx, req.(*BindEmailFlowCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindEmailFlowSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEmailFlowSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindEmailFlowSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindEmailFlowSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindEmailFlowSend(ctx, req.(*BindEmailFlowSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindEmailFlowValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEmailFlowValidateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindEmailFlowValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindEmailFlowValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindEmailFlowValidate(ctx, req.(*BindEmailFlowValidateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindOAuthFlowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindOAuthFlowCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindOAuthFlowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindOAuthFlowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindOAuthFlowCreate(ctx, req.(*BindOAuthFlowCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindOAuthFlowValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindOAuthFlowValidateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindOAuthFlowValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindOAuthFlowValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindOAuthFlowValidate(ctx, req.(*BindOAuthFlowValidateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserKycInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserKycInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserKycInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserKycInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserKycInfo(ctx, req.(*GetUserKycInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserKycDetailInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserKycDetailInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserKycDetailInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserKycDetailInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserKycDetailInfo(ctx, req.(*GetUserKycDetailInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetKycAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKycAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetKycAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetKycAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetKycAccessToken(ctx, req.(*GetKycAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UploadKycResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadKycResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UploadKycResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UploadKycResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UploadKycResult(ctx, req.(*UploadKycResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateKycDetailPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateKycDetailPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateKycDetailPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateKycDetailPending(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateKycDetailAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateKycDetailAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateKycDetailAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateKycDetailAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CloseAccountPreCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAccountPreCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CloseAccountPreCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CloseAccountPreCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CloseAccountPreCheck(ctx, req.(*CloseAccountPreCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CloseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CloseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CloseAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CloseAccount(ctx, req.(*CloseAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLimitsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserLimits(ctx, req.(*GetUserLimitsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserSavedWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSavedWalletsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserSavedWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserSavedWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserSavedWallets(ctx, req.(*GetUserSavedWalletsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserAddSavedWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddSavedWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserAddSavedWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserAddSavedWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserAddSavedWallet(ctx, req.(*UserAddSavedWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserDeleteSavedWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteSavedWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserDeleteSavedWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserDeleteSavedWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserDeleteSavedWallet(ctx, req.(*UserDeleteSavedWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserUpdateSavedWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateSavedWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserUpdateSavedWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserUpdateSavedWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserUpdateSavedWallet(ctx, req.(*UserUpdateSavedWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_BindInviter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindInviterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).BindInviter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_BindInviter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).BindInviter(ctx, req.(*BindInviterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSupportCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSupportCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetSupportCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSupportCountries(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.service.v1.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignFlowCreate",
			Handler:    _User_SignFlowCreate_Handler,
		},
		{
			MethodName: "SignFlowSend",
			Handler:    _User_SignFlowSend_Handler,
		},
		{
			MethodName: "SignFlowValidate",
			Handler:    _User_SignFlowValidate_Handler,
		},
		{
			MethodName: "LoginByPassword",
			Handler:    _User_LoginByPassword_Handler,
		},
		{
			MethodName: "CheckAccessToken",
			Handler:    _User_CheckAccessToken_Handler,
		},
		{
			MethodName: "GetAccessToken",
			Handler:    _User_GetAccessToken_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "QueryUserInfo",
			Handler:    _User_QueryUserInfo_Handler,
		},
		{
			MethodName: "GetUserMobile",
			Handler:    _User_GetUserMobile_Handler,
		},
		{
			MethodName: "GetUserEmail",
			Handler:    _User_GetUserEmail_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _User_CheckUsername_Handler,
		},
		{
			MethodName: "SetupUsername",
			Handler:    _User_SetupUsername_Handler,
		},
		{
			MethodName: "SetupNickname",
			Handler:    _User_SetupNickname_Handler,
		},
		{
			MethodName: "SetupDob",
			Handler:    _User_SetupDob_Handler,
		},
		{
			MethodName: "SetupAvatar",
			Handler:    _User_SetupAvatar_Handler,
		},
		{
			MethodName: "UpdateFiatCurrency",
			Handler:    _User_UpdateFiatCurrency_Handler,
		},
		{
			MethodName: "UpdateNotificationOn",
			Handler:    _User_UpdateNotificationOn_Handler,
		},
		{
			MethodName: "SetupPassword",
			Handler:    _User_SetupPassword_Handler,
		},
		{
			MethodName: "BindEmailFlowCreate",
			Handler:    _User_BindEmailFlowCreate_Handler,
		},
		{
			MethodName: "BindEmailFlowSend",
			Handler:    _User_BindEmailFlowSend_Handler,
		},
		{
			MethodName: "BindEmailFlowValidate",
			Handler:    _User_BindEmailFlowValidate_Handler,
		},
		{
			MethodName: "BindOAuthFlowCreate",
			Handler:    _User_BindOAuthFlowCreate_Handler,
		},
		{
			MethodName: "BindOAuthFlowValidate",
			Handler:    _User_BindOAuthFlowValidate_Handler,
		},
		{
			MethodName: "GetUserKycInfo",
			Handler:    _User_GetUserKycInfo_Handler,
		},
		{
			MethodName: "GetUserKycDetailInfo",
			Handler:    _User_GetUserKycDetailInfo_Handler,
		},
		{
			MethodName: "GetKycAccessToken",
			Handler:    _User_GetKycAccessToken_Handler,
		},
		{
			MethodName: "UploadKycResult",
			Handler:    _User_UploadKycResult_Handler,
		},
		{
			MethodName: "UpdateKycDetailPending",
			Handler:    _User_UpdateKycDetailPending_Handler,
		},
		{
			MethodName: "UpdateKycDetailAll",
			Handler:    _User_UpdateKycDetailAll_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _User_Logout_Handler,
		},
		{
			MethodName: "CloseAccountPreCheck",
			Handler:    _User_CloseAccountPreCheck_Handler,
		},
		{
			MethodName: "CloseAccount",
			Handler:    _User_CloseAccount_Handler,
		},
		{
			MethodName: "GetUserLimits",
			Handler:    _User_GetUserLimits_Handler,
		},
		{
			MethodName: "GetUserSavedWallets",
			Handler:    _User_GetUserSavedWallets_Handler,
		},
		{
			MethodName: "UserAddSavedWallet",
			Handler:    _User_UserAddSavedWallet_Handler,
		},
		{
			MethodName: "UserDeleteSavedWallet",
			Handler:    _User_UserDeleteSavedWallet_Handler,
		},
		{
			MethodName: "UserUpdateSavedWallet",
			Handler:    _User_UserUpdateSavedWallet_Handler,
		},
		{
			MethodName: "BindInviter",
			Handler:    _User_BindInviter_Handler,
		},
		{
			MethodName: "GetSupportCountries",
			Handler:    _User_GetSupportCountries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wello-account/user.proto",
}
