// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: wello-fiat-hub/util/v1/util.proto

package util

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/liberty-group-tech/wello-proto/wello-fiat-hub/common/v1"
	v11 "github.com/liberty-group-tech/wello-proto/wello-fiat-hub/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpGeoLookupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpGeoLookupReq) Reset() {
	*x = IpGeoLookupReq{}
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpGeoLookupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpGeoLookupReq) ProtoMessage() {}

func (x *IpGeoLookupReq) ProtoReflect() protoreflect.Message {
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpGeoLookupReq.ProtoReflect.Descriptor instead.
func (*IpGeoLookupReq) Descriptor() ([]byte, []int) {
	return file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP(), []int{0}
}

func (x *IpGeoLookupReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type IpGeoLookupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName   string                 `protobuf:"bytes,3,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timezone      string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpGeoLookupReply) Reset() {
	*x = IpGeoLookupReply{}
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpGeoLookupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpGeoLookupReply) ProtoMessage() {}

func (x *IpGeoLookupReply) ProtoReflect() protoreflect.Message {
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpGeoLookupReply.ProtoReflect.Descriptor instead.
func (*IpGeoLookupReply) Descriptor() ([]byte, []int) {
	return file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP(), []int{1}
}

func (x *IpGeoLookupReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpGeoLookupReply) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *IpGeoLookupReply) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *IpGeoLookupReply) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IpGeoLookupReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IpGeoLookupReply) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *IpGeoLookupReply) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *IpGeoLookupReply) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetFlwBankListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlwBankListReq) Reset() {
	*x = GetFlwBankListReq{}
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlwBankListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlwBankListReq) ProtoMessage() {}

func (x *GetFlwBankListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlwBankListReq.ProtoReflect.Descriptor instead.
func (*GetFlwBankListReq) Descriptor() ([]byte, []int) {
	return file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlwBankListReq) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetFlwBankListReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Banks         []*GetFlwBankListReply_Bank `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlwBankListReply) Reset() {
	*x = GetFlwBankListReply{}
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlwBankListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlwBankListReply) ProtoMessage() {}

func (x *GetFlwBankListReply) ProtoReflect() protoreflect.Message {
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlwBankListReply.ProtoReflect.Descriptor instead.
func (*GetFlwBankListReply) Descriptor() ([]byte, []int) {
	return file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlwBankListReply) GetBanks() []*GetFlwBankListReply_Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

type GetFlwBankListReply_Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlwBankListReply_Bank) Reset() {
	*x = GetFlwBankListReply_Bank{}
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlwBankListReply_Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlwBankListReply_Bank) ProtoMessage() {}

func (x *GetFlwBankListReply_Bank) ProtoReflect() protoreflect.Message {
	mi := &file_wello_fiat_hub_util_v1_util_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlwBankListReply_Bank.ProtoReflect.Descriptor instead.
func (*GetFlwBankListReply_Bank) Descriptor() ([]byte, []int) {
	return file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetFlwBankListReply_Bank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFlwBankListReply_Bank) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetFlwBankListReply_Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_wello_fiat_hub_util_v1_util_proto protoreflect.FileDescriptor

const file_wello_fiat_hub_util_v1_util_proto_rawDesc = "" +
	"\n" +
	"!wello-fiat-hub/util/v1/util.proto\x12\x0ffiathub.util.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a-wello-fiat-hub/shared/v1/payment_method.proto\x1a%wello-fiat-hub/common/v1/common.proto\" \n" +
	"\x0eIpGeoLookupReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xea\x01\n" +
	"\x10IpGeoLookupReply\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x03 \x01(\tR\vcountryName\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\"@\n" +
	"\x11GetFlwBankListReq\x12+\n" +
	"\acountry\x18\x01 \x01(\tB\x11\xfaB\x0er\f2\n" +
	"^[A-Z]{2}$R\acountry\"\x96\x01\n" +
	"\x13GetFlwBankListReply\x12?\n" +
	"\x05banks\x18\x01 \x03(\v2).fiathub.util.v1.GetFlwBankListReply.BankR\x05banks\x1a>\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2\xd3\x05\n" +
	"\x04Util\x12s\n" +
	"\vIpGeoLookup\x12\x1f.fiathub.util.v1.IpGeoLookupReq\x1a!.fiathub.util.v1.IpGeoLookupReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/util/ip_geo_lookup/{ip}\x12\x81\x01\n" +
	"\x0eGetFlwBankList\x12\".fiathub.util.v1.GetFlwBankListReq\x1a$.fiathub.util.v1.GetFlwBankListReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/util/flw/bank_list/{country}\x12`\n" +
	"\tGetFxRate\x12\x1b.common.v1.GetFxRateRequest\x1a\x19.common.v1.GetFxRateReply\"\x1b\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/util/fx/rate\x88\x02\x01\x12x\n" +
	"\x13DeletePaymentMethod\x12\".common.v1.GetPaymentMethodRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1c*\x1a/util/payment_methods/{id}\x88\x02\x01\x12w\n" +
	"\x10GetPaymentMethod\x12\".common.v1.GetPaymentMethodRequest\x1a\x18.shared.v1.PaymentMethod\"%\x82\xd3\xe4\x93\x02\x1c\x12\x1a/util/payment_methods/{id}\x88\x02\x01\x12}\n" +
	"\x11GetPaymentMethods\x12#.common.v1.GetPaymentMethodsRequest\x1a!.common.v1.GetPaymentMethodsReply\" \x82\xd3\xe4\x93\x02\x17\x12\x15/util/payment_methods\x88\x02\x01B~\n" +
	"\x1fdev.kratos.api.fiat-hub.util.v1B\x12FiatHubUtilProtoV1P\x01ZEgithub.com/liberty-group-tech/wello-proto/wello-fiat-hub/util/v1;utilb\x06proto3"

var (
	file_wello_fiat_hub_util_v1_util_proto_rawDescOnce sync.Once
	file_wello_fiat_hub_util_v1_util_proto_rawDescData []byte
)

func file_wello_fiat_hub_util_v1_util_proto_rawDescGZIP() []byte {
	file_wello_fiat_hub_util_v1_util_proto_rawDescOnce.Do(func() {
		file_wello_fiat_hub_util_v1_util_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wello_fiat_hub_util_v1_util_proto_rawDesc), len(file_wello_fiat_hub_util_v1_util_proto_rawDesc)))
	})
	return file_wello_fiat_hub_util_v1_util_proto_rawDescData
}

var file_wello_fiat_hub_util_v1_util_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wello_fiat_hub_util_v1_util_proto_goTypes = []any{
	(*IpGeoLookupReq)(nil),              // 0: fiathub.util.v1.IpGeoLookupReq
	(*IpGeoLookupReply)(nil),            // 1: fiathub.util.v1.IpGeoLookupReply
	(*GetFlwBankListReq)(nil),           // 2: fiathub.util.v1.GetFlwBankListReq
	(*GetFlwBankListReply)(nil),         // 3: fiathub.util.v1.GetFlwBankListReply
	(*GetFlwBankListReply_Bank)(nil),    // 4: fiathub.util.v1.GetFlwBankListReply.Bank
	(*v1.GetFxRateRequest)(nil),         // 5: common.v1.GetFxRateRequest
	(*v1.GetPaymentMethodRequest)(nil),  // 6: common.v1.GetPaymentMethodRequest
	(*v1.GetPaymentMethodsRequest)(nil), // 7: common.v1.GetPaymentMethodsRequest
	(*v1.GetFxRateReply)(nil),           // 8: common.v1.GetFxRateReply
	(*emptypb.Empty)(nil),               // 9: google.protobuf.Empty
	(*v11.PaymentMethod)(nil),           // 10: shared.v1.PaymentMethod
	(*v1.GetPaymentMethodsReply)(nil),   // 11: common.v1.GetPaymentMethodsReply
}
var file_wello_fiat_hub_util_v1_util_proto_depIdxs = []int32{
	4,  // 0: fiathub.util.v1.GetFlwBankListReply.banks:type_name -> fiathub.util.v1.GetFlwBankListReply.Bank
	0,  // 1: fiathub.util.v1.Util.IpGeoLookup:input_type -> fiathub.util.v1.IpGeoLookupReq
	2,  // 2: fiathub.util.v1.Util.GetFlwBankList:input_type -> fiathub.util.v1.GetFlwBankListReq
	5,  // 3: fiathub.util.v1.Util.GetFxRate:input_type -> common.v1.GetFxRateRequest
	6,  // 4: fiathub.util.v1.Util.DeletePaymentMethod:input_type -> common.v1.GetPaymentMethodRequest
	6,  // 5: fiathub.util.v1.Util.GetPaymentMethod:input_type -> common.v1.GetPaymentMethodRequest
	7,  // 6: fiathub.util.v1.Util.GetPaymentMethods:input_type -> common.v1.GetPaymentMethodsRequest
	1,  // 7: fiathub.util.v1.Util.IpGeoLookup:output_type -> fiathub.util.v1.IpGeoLookupReply
	3,  // 8: fiathub.util.v1.Util.GetFlwBankList:output_type -> fiathub.util.v1.GetFlwBankListReply
	8,  // 9: fiathub.util.v1.Util.GetFxRate:output_type -> common.v1.GetFxRateReply
	9,  // 10: fiathub.util.v1.Util.DeletePaymentMethod:output_type -> google.protobuf.Empty
	10, // 11: fiathub.util.v1.Util.GetPaymentMethod:output_type -> shared.v1.PaymentMethod
	11, // 12: fiathub.util.v1.Util.GetPaymentMethods:output_type -> common.v1.GetPaymentMethodsReply
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_wello_fiat_hub_util_v1_util_proto_init() }
func file_wello_fiat_hub_util_v1_util_proto_init() {
	if File_wello_fiat_hub_util_v1_util_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wello_fiat_hub_util_v1_util_proto_rawDesc), len(file_wello_fiat_hub_util_v1_util_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wello_fiat_hub_util_v1_util_proto_goTypes,
		DependencyIndexes: file_wello_fiat_hub_util_v1_util_proto_depIdxs,
		MessageInfos:      file_wello_fiat_hub_util_v1_util_proto_msgTypes,
	}.Build()
	File_wello_fiat_hub_util_v1_util_proto = out.File
	file_wello_fiat_hub_util_v1_util_proto_goTypes = nil
	file_wello_fiat_hub_util_v1_util_proto_depIdxs = nil
}
