// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: wello-fiat-hub/util/v1/util.proto

package util

import (
	context "context"
	v1 "github.com/liberty-group-tech/wello-proto/wello-fiat-hub/common/v1"
	v11 "github.com/liberty-group-tech/wello-proto/wello-fiat-hub/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Util_IpGeoLookup_FullMethodName         = "/fiathub.util.v1.Util/IpGeoLookup"
	Util_GetFlwBankList_FullMethodName      = "/fiathub.util.v1.Util/GetFlwBankList"
	Util_GetFxRate_FullMethodName           = "/fiathub.util.v1.Util/GetFxRate"
	Util_DeletePaymentMethod_FullMethodName = "/fiathub.util.v1.Util/DeletePaymentMethod"
	Util_GetPaymentMethod_FullMethodName    = "/fiathub.util.v1.Util/GetPaymentMethod"
	Util_GetPaymentMethods_FullMethodName   = "/fiathub.util.v1.Util/GetPaymentMethods"
)

// UtilClient is the client API for Util service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UtilClient interface {
	IpGeoLookup(ctx context.Context, in *IpGeoLookupReq, opts ...grpc.CallOption) (*IpGeoLookupReply, error)
	GetFlwBankList(ctx context.Context, in *GetFlwBankListReq, opts ...grpc.CallOption) (*GetFlwBankListReply, error)
	// Deprecated: Do not use.
	GetFxRate(ctx context.Context, in *v1.GetFxRateRequest, opts ...grpc.CallOption) (*v1.GetFxRateReply, error)
	// Deprecated: Do not use.
	DeletePaymentMethod(ctx context.Context, in *v1.GetPaymentMethodRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	GetPaymentMethod(ctx context.Context, in *v1.GetPaymentMethodRequest, opts ...grpc.CallOption) (*v11.PaymentMethod, error)
	// Deprecated: Do not use.
	GetPaymentMethods(ctx context.Context, in *v1.GetPaymentMethodsRequest, opts ...grpc.CallOption) (*v1.GetPaymentMethodsReply, error)
}

type utilClient struct {
	cc grpc.ClientConnInterface
}

func NewUtilClient(cc grpc.ClientConnInterface) UtilClient {
	return &utilClient{cc}
}

func (c *utilClient) IpGeoLookup(ctx context.Context, in *IpGeoLookupReq, opts ...grpc.CallOption) (*IpGeoLookupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpGeoLookupReply)
	err := c.cc.Invoke(ctx, Util_IpGeoLookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilClient) GetFlwBankList(ctx context.Context, in *GetFlwBankListReq, opts ...grpc.CallOption) (*GetFlwBankListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlwBankListReply)
	err := c.cc.Invoke(ctx, Util_GetFlwBankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *utilClient) GetFxRate(ctx context.Context, in *v1.GetFxRateRequest, opts ...grpc.CallOption) (*v1.GetFxRateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetFxRateReply)
	err := c.cc.Invoke(ctx, Util_GetFxRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *utilClient) DeletePaymentMethod(ctx context.Context, in *v1.GetPaymentMethodRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Util_DeletePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *utilClient) GetPaymentMethod(ctx context.Context, in *v1.GetPaymentMethodRequest, opts ...grpc.CallOption) (*v11.PaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.PaymentMethod)
	err := c.cc.Invoke(ctx, Util_GetPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *utilClient) GetPaymentMethods(ctx context.Context, in *v1.GetPaymentMethodsRequest, opts ...grpc.CallOption) (*v1.GetPaymentMethodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetPaymentMethodsReply)
	err := c.cc.Invoke(ctx, Util_GetPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UtilServer is the server API for Util service.
// All implementations must embed UnimplementedUtilServer
// for forward compatibility.
type UtilServer interface {
	IpGeoLookup(context.Context, *IpGeoLookupReq) (*IpGeoLookupReply, error)
	GetFlwBankList(context.Context, *GetFlwBankListReq) (*GetFlwBankListReply, error)
	// Deprecated: Do not use.
	GetFxRate(context.Context, *v1.GetFxRateRequest) (*v1.GetFxRateReply, error)
	// Deprecated: Do not use.
	DeletePaymentMethod(context.Context, *v1.GetPaymentMethodRequest) (*emptypb.Empty, error)
	// Deprecated: Do not use.
	GetPaymentMethod(context.Context, *v1.GetPaymentMethodRequest) (*v11.PaymentMethod, error)
	// Deprecated: Do not use.
	GetPaymentMethods(context.Context, *v1.GetPaymentMethodsRequest) (*v1.GetPaymentMethodsReply, error)
	mustEmbedUnimplementedUtilServer()
}

// UnimplementedUtilServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUtilServer struct{}

func (UnimplementedUtilServer) IpGeoLookup(context.Context, *IpGeoLookupReq) (*IpGeoLookupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IpGeoLookup not implemented")
}
func (UnimplementedUtilServer) GetFlwBankList(context.Context, *GetFlwBankListReq) (*GetFlwBankListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlwBankList not implemented")
}
func (UnimplementedUtilServer) GetFxRate(context.Context, *v1.GetFxRateRequest) (*v1.GetFxRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFxRate not implemented")
}
func (UnimplementedUtilServer) DeletePaymentMethod(context.Context, *v1.GetPaymentMethodRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePaymentMethod not implemented")
}
func (UnimplementedUtilServer) GetPaymentMethod(context.Context, *v1.GetPaymentMethodRequest) (*v11.PaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethod not implemented")
}
func (UnimplementedUtilServer) GetPaymentMethods(context.Context, *v1.GetPaymentMethodsRequest) (*v1.GetPaymentMethodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethods not implemented")
}
func (UnimplementedUtilServer) mustEmbedUnimplementedUtilServer() {}
func (UnimplementedUtilServer) testEmbeddedByValue()              {}

// UnsafeUtilServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UtilServer will
// result in compilation errors.
type UnsafeUtilServer interface {
	mustEmbedUnimplementedUtilServer()
}

func RegisterUtilServer(s grpc.ServiceRegistrar, srv UtilServer) {
	// If the following call pancis, it indicates UnimplementedUtilServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Util_ServiceDesc, srv)
}

func _Util_IpGeoLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpGeoLookupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).IpGeoLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_IpGeoLookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).IpGeoLookup(ctx, req.(*IpGeoLookupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_GetFlwBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlwBankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).GetFlwBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_GetFlwBankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).GetFlwBankList(ctx, req.(*GetFlwBankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_GetFxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetFxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).GetFxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_GetFxRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).GetFxRate(ctx, req.(*v1.GetFxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_DeletePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).DeletePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_DeletePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).DeletePaymentMethod(ctx, req.(*v1.GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_GetPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).GetPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_GetPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).GetPaymentMethod(ctx, req.(*v1.GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Util_GetPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilServer).GetPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Util_GetPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilServer).GetPaymentMethods(ctx, req.(*v1.GetPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Util_ServiceDesc is the grpc.ServiceDesc for Util service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Util_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fiathub.util.v1.Util",
	HandlerType: (*UtilServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IpGeoLookup",
			Handler:    _Util_IpGeoLookup_Handler,
		},
		{
			MethodName: "GetFlwBankList",
			Handler:    _Util_GetFlwBankList_Handler,
		},
		{
			MethodName: "GetFxRate",
			Handler:    _Util_GetFxRate_Handler,
		},
		{
			MethodName: "DeletePaymentMethod",
			Handler:    _Util_DeletePaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethod",
			Handler:    _Util_GetPaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethods",
			Handler:    _Util_GetPaymentMethods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wello-fiat-hub/util/v1/util.proto",
}
