// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: wello-fiat-hub/common/v1/common.proto

package common

import (
	context "context"
	v1 "github.com/liberty-group-tech/wello-proto/wello-fiat-hub/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Common_GetCardInfo_FullMethodName         = "/common.v1.Common/GetCardInfo"
	Common_GetFxRate_FullMethodName           = "/common.v1.Common/GetFxRate"
	Common_DeletePaymentMethod_FullMethodName = "/common.v1.Common/DeletePaymentMethod"
	Common_GetPaymentMethod_FullMethodName    = "/common.v1.Common/GetPaymentMethod"
	Common_GetPaymentMethods_FullMethodName   = "/common.v1.Common/GetPaymentMethods"
	Common_ValidateCard_FullMethodName        = "/common.v1.Common/ValidateCard"
)

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonClient interface {
	GetCardInfo(ctx context.Context, in *GetCardInfoRequest, opts ...grpc.CallOption) (*GetCardInfoReply, error)
	GetFxRate(ctx context.Context, in *GetFxRateRequest, opts ...grpc.CallOption) (*GetFxRateReply, error)
	DeletePaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*v1.PaymentMethod, error)
	GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsReply, error)
	ValidateCard(ctx context.Context, in *ValidateCardRequest, opts ...grpc.CallOption) (*ValidateCardReply, error)
}

type commonClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonClient(cc grpc.ClientConnInterface) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) GetCardInfo(ctx context.Context, in *GetCardInfoRequest, opts ...grpc.CallOption) (*GetCardInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardInfoReply)
	err := c.cc.Invoke(ctx, Common_GetCardInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) GetFxRate(ctx context.Context, in *GetFxRateRequest, opts ...grpc.CallOption) (*GetFxRateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFxRateReply)
	err := c.cc.Invoke(ctx, Common_GetFxRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) DeletePaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Common_DeletePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*v1.PaymentMethod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.PaymentMethod)
	err := c.cc.Invoke(ctx, Common_GetPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodsReply)
	err := c.cc.Invoke(ctx, Common_GetPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) ValidateCard(ctx context.Context, in *ValidateCardRequest, opts ...grpc.CallOption) (*ValidateCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCardReply)
	err := c.cc.Invoke(ctx, Common_ValidateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
// All implementations must embed UnimplementedCommonServer
// for forward compatibility.
type CommonServer interface {
	GetCardInfo(context.Context, *GetCardInfoRequest) (*GetCardInfoReply, error)
	GetFxRate(context.Context, *GetFxRateRequest) (*GetFxRateReply, error)
	DeletePaymentMethod(context.Context, *GetPaymentMethodRequest) (*emptypb.Empty, error)
	GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*v1.PaymentMethod, error)
	GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsReply, error)
	ValidateCard(context.Context, *ValidateCardRequest) (*ValidateCardReply, error)
	mustEmbedUnimplementedCommonServer()
}

// UnimplementedCommonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonServer struct{}

func (UnimplementedCommonServer) GetCardInfo(context.Context, *GetCardInfoRequest) (*GetCardInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardInfo not implemented")
}
func (UnimplementedCommonServer) GetFxRate(context.Context, *GetFxRateRequest) (*GetFxRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFxRate not implemented")
}
func (UnimplementedCommonServer) DeletePaymentMethod(context.Context, *GetPaymentMethodRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePaymentMethod not implemented")
}
func (UnimplementedCommonServer) GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*v1.PaymentMethod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethod not implemented")
}
func (UnimplementedCommonServer) GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethods not implemented")
}
func (UnimplementedCommonServer) ValidateCard(context.Context, *ValidateCardRequest) (*ValidateCardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCard not implemented")
}
func (UnimplementedCommonServer) mustEmbedUnimplementedCommonServer() {}
func (UnimplementedCommonServer) testEmbeddedByValue()                {}

// UnsafeCommonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServer will
// result in compilation errors.
type UnsafeCommonServer interface {
	mustEmbedUnimplementedCommonServer()
}

func RegisterCommonServer(s grpc.ServiceRegistrar, srv CommonServer) {
	// If the following call pancis, it indicates UnimplementedCommonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Common_ServiceDesc, srv)
}

func _Common_GetCardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).GetCardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_GetCardInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).GetCardInfo(ctx, req.(*GetCardInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_GetFxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).GetFxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_GetFxRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).GetFxRate(ctx, req.(*GetFxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_DeletePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).DeletePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_DeletePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).DeletePaymentMethod(ctx, req.(*GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_GetPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).GetPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_GetPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).GetPaymentMethod(ctx, req.(*GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_GetPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).GetPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_GetPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).GetPaymentMethods(ctx, req.(*GetPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_ValidateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).ValidateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_ValidateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).ValidateCard(ctx, req.(*ValidateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Common_ServiceDesc is the grpc.ServiceDesc for Common service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Common_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.v1.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardInfo",
			Handler:    _Common_GetCardInfo_Handler,
		},
		{
			MethodName: "GetFxRate",
			Handler:    _Common_GetFxRate_Handler,
		},
		{
			MethodName: "DeletePaymentMethod",
			Handler:    _Common_DeletePaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethod",
			Handler:    _Common_GetPaymentMethod_Handler,
		},
		{
			MethodName: "GetPaymentMethods",
			Handler:    _Common_GetPaymentMethods_Handler,
		},
		{
			MethodName: "ValidateCard",
			Handler:    _Common_ValidateCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wello-fiat-hub/common/v1/common.proto",
}
