// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package apierrs

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 成功
func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Success.String() && e.Code == 500
}

// 成功
func ErrorSuccess(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_Success.String(), fmt.Sprintf(format, args...))
}

// Common错误
func IsCommonPanic(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonPanic.String() && e.Code == 500
}

// Common错误
func ErrorCommonPanic(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonPanic.String(), fmt.Sprintf(format, args...))
}

// 请求参数错误,一般是缺失或者格式不对，不牵扯逻辑[一般是App出问题]
func IsCommonBadRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonBadRequest.String() && e.Code == 500
}

// 请求参数错误,一般是缺失或者格式不对，不牵扯逻辑[一般是App出问题]
func ErrorCommonBadRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonBadRequest.String(), fmt.Sprintf(format, args...))
}

// 未授权，也就是登录失效
func IsCommonUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonUnauthorized.String() && e.Code == 500
}

// 未授权，也就是登录失效
func ErrorCommonUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonUnauthorized.String(), fmt.Sprintf(format, args...))
}

// 服务器内部错误，逻辑错误
func IsCommonServerErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonServerErr.String() && e.Code == 500
}

// 服务器内部错误，逻辑错误
func ErrorCommonServerErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonServerErr.String(), fmt.Sprintf(format, args...))
}

// 未知错误
func IsCommonUnknownErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonUnknownErr.String() && e.Code == 500
}

// 未知错误
func ErrorCommonUnknownErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonUnknownErr.String(), fmt.Sprintf(format, args...))
}

// 内部微服务暂时无法访问
func IsCommonServiceOverloaded(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonServiceOverloaded.String() && e.Code == 500
}

// 内部微服务暂时无法访问
func ErrorCommonServiceOverloaded(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonServiceOverloaded.String(), fmt.Sprintf(format, args...))
}

// 数据库访问失败
func IsCommonMysqlErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonMysqlErr.String() && e.Code == 500
}

// 数据库访问失败
func ErrorCommonMysqlErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonMysqlErr.String(), fmt.Sprintf(format, args...))
}

// redis访问失败
func IsCommonRedisErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonRedisErr.String() && e.Code == 500
}

// redis访问失败
func ErrorCommonRedisErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonRedisErr.String(), fmt.Sprintf(format, args...))
}

// 分布式锁获取失败
func IsCommonRedisLockErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonRedisLockErr.String() && e.Code == 500
}

// 分布式锁获取失败
func ErrorCommonRedisLockErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonRedisLockErr.String(), fmt.Sprintf(format, args...))
}

// 内部调用参数错误
func IsCommonServiceCallBadRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonServiceCallBadRequest.String() && e.Code == 500
}

// 内部调用参数错误
func ErrorCommonServiceCallBadRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonServiceCallBadRequest.String(), fmt.Sprintf(format, args...))
}

// 一些重试可能解决的错误
func IsCommonRetry(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonRetry.String() && e.Code == 500
}

// 一些重试可能解决的错误
func ErrorCommonRetry(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonRetry.String(), fmt.Sprintf(format, args...))
}

// 找不到记录
func IsCommonRecordNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonRecordNotFound.String() && e.Code == 500
}

// 找不到记录
func ErrorCommonRecordNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonRecordNotFound.String(), fmt.Sprintf(format, args...))
}

// 数字格式错误
func IsCommonNumberFormatErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonNumberFormatErr.String() && e.Code == 500
}

// 数字格式错误
func ErrorCommonNumberFormatErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonNumberFormatErr.String(), fmt.Sprintf(format, args...))
}

// 无权限操作
func IsCommonForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonForbidden.String() && e.Code == 500
}

// 无权限操作
func ErrorCommonForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonForbidden.String(), fmt.Sprintf(format, args...))
}

// vendor call 错误
func IsCommonVendorCallErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CommonVendorCallErr.String() && e.Code == 500
}

// vendor call 错误
func ErrorCommonVendorCallErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CommonVendorCallErr.String(), fmt.Sprintf(format, args...))
}

// User模块错误
func IsUserSignFlowTypeNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserSignFlowTypeNotSupport.String() && e.Code == 500
}

// User模块错误
func ErrorUserSignFlowTypeNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserSignFlowTypeNotSupport.String(), fmt.Sprintf(format, args...))
}

// 手机区号不支持
func IsUserMobileCodeNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMobileCodeNotSupport.String() && e.Code == 500
}

// 手机区号不支持
func ErrorUserMobileCodeNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMobileCodeNotSupport.String(), fmt.Sprintf(format, args...))
}

// 手机号格式错误(一般就是没传)
func IsUserMobileFormatErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMobileFormatErr.String() && e.Code == 500
}

// 手机号格式错误(一般就是没传)
func ErrorUserMobileFormatErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMobileFormatErr.String(), fmt.Sprintf(format, args...))
}

// 手机号已经注册
func IsUserMobileAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMobileAlreadyExist.String() && e.Code == 500
}

// 手机号已经注册
func ErrorUserMobileAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMobileAlreadyExist.String(), fmt.Sprintf(format, args...))
}

// 登录/注册Flow找不到或者已经过期
func IsUserSignFlowNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserSignFlowNotFound.String() && e.Code == 500
}

// 登录/注册Flow找不到或者已经过期
func ErrorUserSignFlowNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserSignFlowNotFound.String(), fmt.Sprintf(format, args...))
}

// 验证码发送次数超过限制
func IsUserVerifyCodeSendTooMany(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserVerifyCodeSendTooMany.String() && e.Code == 500
}

// 验证码发送次数超过限制
func ErrorUserVerifyCodeSendTooMany(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserVerifyCodeSendTooMany.String(), fmt.Sprintf(format, args...))
}

// 验证码发送过于频繁
func IsUserVerifyCodeSendFrequent(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserVerifyCodeSendFrequent.String() && e.Code == 500
}

// 验证码发送过于频繁
func ErrorUserVerifyCodeSendFrequent(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserVerifyCodeSendFrequent.String(), fmt.Sprintf(format, args...))
}

// 验证码错误次数过多
func IsUserVerifyCodeErrorTooMany(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserVerifyCodeErrorTooMany.String() && e.Code == 500
}

// 验证码错误次数过多
func ErrorUserVerifyCodeErrorTooMany(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserVerifyCodeErrorTooMany.String(), fmt.Sprintf(format, args...))
}

// 验证码错误
func IsUserVerifyCodeError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserVerifyCodeError.String() && e.Code == 500
}

// 验证码错误
func ErrorUserVerifyCodeError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserVerifyCodeError.String(), fmt.Sprintf(format, args...))
}

// 用户找不到
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserNotFound.String() && e.Code == 500
}

// 用户找不到
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserNotFound.String(), fmt.Sprintf(format, args...))
}

// 用户被冻结
func IsUserStatusDisabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserStatusDisabled.String() && e.Code == 500
}

// 用户被冻结
func ErrorUserStatusDisabled(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserStatusDisabled.String(), fmt.Sprintf(format, args...))
}

// 用户已经注销
func IsUserStatusDeleted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserStatusDeleted.String() && e.Code == 500
}

// 用户已经注销
func ErrorUserStatusDeleted(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserStatusDeleted.String(), fmt.Sprintf(format, args...))
}

// 手机号未注册
func IsUserMobileNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMobileNotExist.String() && e.Code == 500
}

// 手机号未注册
func ErrorUserMobileNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMobileNotExist.String(), fmt.Sprintf(format, args...))
}

// Username已经存在
func IsUserUsernameExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserUsernameExist.String() && e.Code == 500
}

// Username已经存在
func ErrorUserUsernameExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserUsernameExist.String(), fmt.Sprintf(format, args...))
}

// 钱包地址已经被别人绑定
func IsUserCryptoWalletAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserCryptoWalletAlreadyExist.String() && e.Code == 500
}

// 钱包地址已经被别人绑定
func ErrorUserCryptoWalletAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserCryptoWalletAlreadyExist.String(), fmt.Sprintf(format, args...))
}

// 用户已经绑定CryptoWallet
func IsUserAlreadyBindCryptoWallet(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyBindCryptoWallet.String() && e.Code == 500
}

// 用户已经绑定CryptoWallet
func ErrorUserAlreadyBindCryptoWallet(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyBindCryptoWallet.String(), fmt.Sprintf(format, args...))
}

// 必须携带旧密码
func IsUserMustPassOldPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMustPassOldPassword.String() && e.Code == 500
}

// 必须携带旧密码
func ErrorUserMustPassOldPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMustPassOldPassword.String(), fmt.Sprintf(format, args...))
}

// 旧密码错误
func IsUserOldPasswordError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOldPasswordError.String() && e.Code == 500
}

// 旧密码错误
func ErrorUserOldPasswordError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserOldPasswordError.String(), fmt.Sprintf(format, args...))
}

// 用户已经绑定过Email
func IsUserAlreadyBindEmail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyBindEmail.String() && e.Code == 500
}

// 用户已经绑定过Email
func ErrorUserAlreadyBindEmail(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyBindEmail.String(), fmt.Sprintf(format, args...))
}

// 邮箱已经被注册
func IsUserEmailAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserEmailAlreadyExist.String() && e.Code == 500
}

// 邮箱已经被注册
func ErrorUserEmailAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserEmailAlreadyExist.String(), fmt.Sprintf(format, args...))
}

// 绑定邮箱的Flow找不到
func IsUserBindEmailFlowNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserBindEmailFlowNotFound.String() && e.Code == 500
}

// 绑定邮箱的Flow找不到
func ErrorUserBindEmailFlowNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserBindEmailFlowNotFound.String(), fmt.Sprintf(format, args...))
}

// OAuth2平台不支持
func IsUserOAuthPlatformNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOAuthPlatformNotSupport.String() && e.Code == 500
}

// OAuth2平台不支持
func ErrorUserOAuthPlatformNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserOAuthPlatformNotSupport.String(), fmt.Sprintf(format, args...))
}

// 用户已经绑定OAuth
func IsUserAlreadyBindOAuth(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyBindOAuth.String() && e.Code == 500
}

// 用户已经绑定OAuth
func ErrorUserAlreadyBindOAuth(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyBindOAuth.String(), fmt.Sprintf(format, args...))
}

// 该OAuth已经被别人绑定
func IsUserOAuthAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOAuthAlreadyExist.String() && e.Code == 500
}

// 该OAuth已经被别人绑定
func ErrorUserOAuthAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserOAuthAlreadyExist.String(), fmt.Sprintf(format, args...))
}

// 绑定OAuthFlow过期
func IsUserBindOAuthFlowNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserBindOAuthFlowNotFound.String() && e.Code == 500
}

// 绑定OAuthFlow过期
func ErrorUserBindOAuthFlowNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserBindOAuthFlowNotFound.String(), fmt.Sprintf(format, args...))
}

// 用户的OAuthToken不合法
func IsUserOAuthTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOAuthTokenInvalid.String() && e.Code == 500
}

// 用户的OAuthToken不合法
func ErrorUserOAuthTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserOAuthTokenInvalid.String(), fmt.Sprintf(format, args...))
}

// 用户暂时无需进行Kyc后续操作
func IsUserKycNoNeed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserKycNoNeed.String() && e.Code == 500
}

// 用户暂时无需进行Kyc后续操作
func ErrorUserKycNoNeed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserKycNoNeed.String(), fmt.Sprintf(format, args...))
}

// 用户已经通过L2 KYC
func IsUserAlreadyKycL2(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyKycL2.String() && e.Code == 500
}

// 用户已经通过L2 KYC
func ErrorUserAlreadyKycL2(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyKycL2.String(), fmt.Sprintf(format, args...))
}

// 用户已经通过L1 KYC
func IsUserAlreadyKycL1(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyKycL1.String() && e.Code == 500
}

// 用户已经通过L1 KYC
func ErrorUserAlreadyKycL1(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyKycL1.String(), fmt.Sprintf(format, args...))
}

// 用户应该先进行L1 KYC
func IsUserShouldPassKycL1First(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserShouldPassKycL1First.String() && e.Code == 500
}

// 用户应该先进行L1 KYC
func ErrorUserShouldPassKycL1First(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserShouldPassKycL1First.String(), fmt.Sprintf(format, args...))
}

// Sumsub请求失败
func IsUserSumsubCallErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserSumsubCallErr.String() && e.Code == 500
}

// Sumsub请求失败
func ErrorUserSumsubCallErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserSumsubCallErr.String(), fmt.Sprintf(format, args...))
}

// 用户没有KYC信息
func IsUserHaveNoKyc(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserHaveNoKyc.String() && e.Code == 500
}

// 用户没有KYC信息
func ErrorUserHaveNoKyc(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserHaveNoKyc.String(), fmt.Sprintf(format, args...))
}

// 用户没有绑定Crypto钱包
func IsUserCryptoWalletNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserCryptoWalletNotExist.String() && e.Code == 500
}

// 用户没有绑定Crypto钱包
func ErrorUserCryptoWalletNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserCryptoWalletNotExist.String(), fmt.Sprintf(format, args...))
}

// 邮箱格式错误
func IsUserEmailFormatError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserEmailFormatError.String() && e.Code == 500
}

// 邮箱格式错误
func ErrorUserEmailFormatError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserEmailFormatError.String(), fmt.Sprintf(format, args...))
}

// 用户邮箱不存在
func IsUserEmailNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserEmailNotExist.String() && e.Code == 500
}

// 用户邮箱不存在
func ErrorUserEmailNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserEmailNotExist.String(), fmt.Sprintf(format, args...))
}

// 尚未注册
func IsUserOAuthNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOAuthNotExist.String() && e.Code == 500
}

// 尚未注册
func ErrorUserOAuthNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserOAuthNotExist.String(), fmt.Sprintf(format, args...))
}

// 用户存在进行中订单
func IsUserHaveUnFinishedOrders(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserHaveUnFinishedOrders.String() && e.Code == 500
}

// 用户存在进行中订单
func ErrorUserHaveUnFinishedOrders(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserHaveUnFinishedOrders.String(), fmt.Sprintf(format, args...))
}

// 用户正在迁移中
func IsUserMigration(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserMigration.String() && e.Code == 500
}

// 用户正在迁移中
func ErrorUserMigration(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserMigration.String(), fmt.Sprintf(format, args...))
}

// Turnkey创建子机构失败
func IsUserTurnkeyCreateSubOrgError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserTurnkeyCreateSubOrgError.String() && e.Code == 500
}

// Turnkey创建子机构失败
func ErrorUserTurnkeyCreateSubOrgError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserTurnkeyCreateSubOrgError.String(), fmt.Sprintf(format, args...))
}

// Turnkey发送OTP失败
func IsUserTurnkeySendOTPError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserTurnkeySendOTPError.String() && e.Code == 500
}

// Turnkey发送OTP失败
func ErrorUserTurnkeySendOTPError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserTurnkeySendOTPError.String(), fmt.Sprintf(format, args...))
}

// Turnkey验证OTP失败
func IsUserTurnkeyVerifyOTPError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserTurnkeyVerifyOTPError.String() && e.Code == 500
}

// Turnkey验证OTP失败
func ErrorUserTurnkeyVerifyOTPError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserTurnkeyVerifyOTPError.String(), fmt.Sprintf(format, args...))
}

// Turnkey调用失败
func IsUserTurnkeyCallError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserTurnkeyCallError.String() && e.Code == 500
}

// Turnkey调用失败
func ErrorUserTurnkeyCallError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserTurnkeyCallError.String(), fmt.Sprintf(format, args...))
}

// Turnkey返回结果错误
func IsUserTurnkeyResultError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserTurnkeyResultError.String() && e.Code == 500
}

// Turnkey返回结果错误
func ErrorUserTurnkeyResultError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserTurnkeyResultError.String(), fmt.Sprintf(format, args...))
}

// 用户已经存在
func IsUserAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyExist.String() && e.Code == 500
}

// 用户已经存在
func ErrorUserAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAlreadyExist.String(), fmt.Sprintf(format, args...))
}

// 账号或密码错误
func IsUserAccountOrPasswordError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAccountOrPasswordError.String() && e.Code == 500
}

// 账号或密码错误
func ErrorUserAccountOrPasswordError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UserAccountOrPasswordError.String(), fmt.Sprintf(format, args...))
}

// Crypto模块错误
func IsCryptoNodeEndpointNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoNodeEndpointNotFound.String() && e.Code == 500
}

// Crypto模块错误
func ErrorCryptoNodeEndpointNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoNodeEndpointNotFound.String(), fmt.Sprintf(format, args...))
}

// CryptoNetwork不支持
func IsCryptoNetworkNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoNetworkNotSupport.String() && e.Code == 500
}

// CryptoNetwork不支持
func ErrorCryptoNetworkNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoNetworkNotSupport.String(), fmt.Sprintf(format, args...))
}

// 地址格式不合法
func IsCryptoAddressNotValid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoAddressNotValid.String() && e.Code == 500
}

// 地址格式不合法
func ErrorCryptoAddressNotValid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoAddressNotValid.String(), fmt.Sprintf(format, args...))
}

// AEON Quote失败
func IsCryptoAEONError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoAEONError.String() && e.Code == 500
}

// AEON Quote失败
func ErrorCryptoAEONError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoAEONError.String(), fmt.Sprintf(format, args...))
}

// MemeQuote找不到
func IsCryptoMemeQuoteNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoMemeQuoteNotFound.String() && e.Code == 500
}

// MemeQuote找不到
func ErrorCryptoMemeQuoteNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoMemeQuoteNotFound.String(), fmt.Sprintf(format, args...))
}

// 获取地址Nonce失败
func IsCryptoGetNonceError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoGetNonceError.String() && e.Code == 500
}

// 获取地址Nonce失败
func ErrorCryptoGetNonceError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoGetNonceError.String(), fmt.Sprintf(format, args...))
}

// 该Token不支持买卖
func IsCryptoMemeTokenNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoMemeTokenNotSupport.String() && e.Code == 500
}

// 该Token不支持买卖
func ErrorCryptoMemeTokenNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoMemeTokenNotSupport.String(), fmt.Sprintf(format, args...))
}

// 要广播的Tx不存在
func IsCryptoTxNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoTxNotFound.String() && e.Code == 500
}

// 要广播的Tx不存在
func ErrorCryptoTxNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoTxNotFound.String(), fmt.Sprintf(format, args...))
}

// 用户签名数据错误
func IsCryptoUserSignedError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoUserSignedError.String() && e.Code == 500
}

// 用户签名数据错误
func ErrorCryptoUserSignedError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoUserSignedError.String(), fmt.Sprintf(format, args...))
}

// 用户地址不符合
func IsCryptoWalletNotEqual(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoWalletNotEqual.String() && e.Code == 500
}

// 用户地址不符合
func ErrorCryptoWalletNotEqual(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoWalletNotEqual.String(), fmt.Sprintf(format, args...))
}

// 不支持的Coin
func IsCryptoCoinNotSupport(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoCoinNotSupport.String() && e.Code == 500
}

// 不支持的Coin
func ErrorCryptoCoinNotSupport(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoCoinNotSupport.String(), fmt.Sprintf(format, args...))
}

// 获取Token余额失败
func IsCryptoGetTokenBalanceError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoGetTokenBalanceError.String() && e.Code == 500
}

// 获取Token余额失败
func ErrorCryptoGetTokenBalanceError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoGetTokenBalanceError.String(), fmt.Sprintf(format, args...))
}

// Token余额不足
func IsCryptoTokenBalanceInsufficient(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoTokenBalanceInsufficient.String() && e.Code == 500
}

// Token余额不足
func ErrorCryptoTokenBalanceInsufficient(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoTokenBalanceInsufficient.String(), fmt.Sprintf(format, args...))
}

// 获取Token授权失败
func IsCryptoGetTokenApproveError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoGetTokenApproveError.String() && e.Code == 500
}

// 获取Token授权失败
func ErrorCryptoGetTokenApproveError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoGetTokenApproveError.String(), fmt.Sprintf(format, args...))
}

// 请先检查授权
func IsCryptoMustCheckApproveFirst(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoMustCheckApproveFirst.String() && e.Code == 500
}

// 请先检查授权
func ErrorCryptoMustCheckApproveFirst(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoMustCheckApproveFirst.String(), fmt.Sprintf(format, args...))
}

// USDC价格异常波动
func IsCryptoPriceAbnormal(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoPriceAbnormal.String() && e.Code == 500
}

// USDC价格异常波动
func ErrorCryptoPriceAbnormal(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoPriceAbnormal.String(), fmt.Sprintf(format, args...))
}

// Call nodereal Error
func IsCryptoNoderealCallError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoNoderealCallError.String() && e.Code == 500
}

// Call nodereal Error
func ErrorCryptoNoderealCallError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoNoderealCallError.String(), fmt.Sprintf(format, args...))
}

// Nodereal返回错误
func IsCryptoNoderealResultError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CryptoNoderealResultError.String() && e.Code == 500
}

// Nodereal返回错误
func ErrorCryptoNoderealResultError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CryptoNoderealResultError.String(), fmt.Sprintf(format, args...))
}

// IP模块错误
func IsIpInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IpInvalid.String() && e.Code == 500
}

// IP模块错误
func ErrorIpInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_IpInvalid.String(), fmt.Sprintf(format, args...))
}

// Risk模块错误
func IsRiskForterCallErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RiskForterCallErr.String() && e.Code == 500
}

// Risk模块错误
func ErrorRiskForterCallErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_RiskForterCallErr.String(), fmt.Sprintf(format, args...))
}

// Forter结果错误
func IsRiskForterResultErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RiskForterResultErr.String() && e.Code == 500
}

// Forter结果错误
func ErrorRiskForterResultErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_RiskForterResultErr.String(), fmt.Sprintf(format, args...))
}

// 未通过注册风险检测
func IsRiskSignupReject(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RiskSignupReject.String() && e.Code == 500
}

// 未通过注册风险检测
func ErrorRiskSignupReject(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_RiskSignupReject.String(), fmt.Sprintf(format, args...))
}

// 未通过登录风险检测
func IsRiskSignInReject(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RiskSignInReject.String() && e.Code == 500
}

// 未通过登录风险检测
func ErrorRiskSignInReject(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_RiskSignInReject.String(), fmt.Sprintf(format, args...))
}

// OCBS模块错误
func IsOcbsQuoteNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsQuoteNotFound.String() && e.Code == 500
}

// OCBS模块错误
func ErrorOcbsQuoteNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsQuoteNotFound.String(), fmt.Sprintf(format, args...))
}

// 汇率错误
func IsOcbsFiatRateInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsFiatRateInvalid.String() && e.Code == 500
}

// 汇率错误
func ErrorOcbsFiatRateInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsFiatRateInvalid.String(), fmt.Sprintf(format, args...))
}

// Quoter找不到
func IsOcbsQuoterNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsQuoterNotFound.String() && e.Code == 500
}

// Quoter找不到
func ErrorOcbsQuoterNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsQuoterNotFound.String(), fmt.Sprintf(format, args...))
}

// 交易限制错误
func IsOcbsTradeLimitError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsTradeLimitError.String() && e.Code == 500
}

// 交易限制错误
func ErrorOcbsTradeLimitError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsTradeLimitError.String(), fmt.Sprintf(format, args...))
}

// 交易对找不到
func IsOcbsPairNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsPairNotFound.String() && e.Code == 500
}

// 交易对找不到
func ErrorOcbsPairNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsPairNotFound.String(), fmt.Sprintf(format, args...))
}

// 交易对手续费配置找不到
func IsOcbsFeeConfigNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsFeeConfigNotFound.String() && e.Code == 500
}

// 交易对手续费配置找不到
func ErrorOcbsFeeConfigNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsFeeConfigNotFound.String(), fmt.Sprintf(format, args...))
}

// 提现最小限制
func IsOcbsSellMinLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsSellMinLimit.String() && e.Code == 500
}

// 提现最小限制
func ErrorOcbsSellMinLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsSellMinLimit.String(), fmt.Sprintf(format, args...))
}

// 提现最大限制
func IsOcbsSellMaxLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsSellMaxLimit.String() && e.Code == 500
}

// 提现最大限制
func ErrorOcbsSellMaxLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsSellMaxLimit.String(), fmt.Sprintf(format, args...))
}

// 充值最小限制
func IsOcbsBuyMinLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsBuyMinLimit.String() && e.Code == 500
}

// 充值最小限制
func ErrorOcbsBuyMinLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsBuyMinLimit.String(), fmt.Sprintf(format, args...))
}

// 充值最大限制
func IsOcbsBuyMaxLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsBuyMaxLimit.String() && e.Code == 500
}

// 充值最大限制
func ErrorOcbsBuyMaxLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsBuyMaxLimit.String(), fmt.Sprintf(format, args...))
}

// LP Vendor错误
func IsOcbsLpVendorError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsLpVendorError.String() && e.Code == 500
}

// LP Vendor错误
func ErrorOcbsLpVendorError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsLpVendorError.String(), fmt.Sprintf(format, args...))
}

// 法币手续费错误
func IsOcbsFiatFeeError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsFiatFeeError.String() && e.Code == 500
}

// 法币手续费错误
func ErrorOcbsFiatFeeError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsFiatFeeError.String(), fmt.Sprintf(format, args...))
}

// 充值限制错误
func IsOcbsDepositLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsDepositLimit.String() && e.Code == 500
}

// 充值限制错误
func ErrorOcbsDepositLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsDepositLimit.String(), fmt.Sprintf(format, args...))
}

// 提现限制错误
func IsOcbsWithdrawLimit(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsWithdrawLimit.String() && e.Code == 500
}

// 提现限制错误
func ErrorOcbsWithdrawLimit(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsWithdrawLimit.String(), fmt.Sprintf(format, args...))
}

// 余额不足
func IsOcbsBalanceInsufficient(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OcbsBalanceInsufficient.String() && e.Code == 500
}

// 余额不足
func ErrorOcbsBalanceInsufficient(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OcbsBalanceInsufficient.String(), fmt.Sprintf(format, args...))
}

// Fiat模块错误
func IsFiatVendorCallError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatVendorCallError.String() && e.Code == 500
}

// Fiat模块错误
func ErrorFiatVendorCallError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatVendorCallError.String(), fmt.Sprintf(format, args...))
}

// 支付渠道结果错误
func IsFiatVendorResultError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatVendorResultError.String() && e.Code == 500
}

// 支付渠道结果错误
func ErrorFiatVendorResultError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatVendorResultError.String(), fmt.Sprintf(format, args...))
}

// 卡片不存在
func IsFiatCardNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatCardNotFound.String() && e.Code == 500
}

// 卡片不存在
func ErrorFiatCardNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatCardNotFound.String(), fmt.Sprintf(format, args...))
}

// 风险检测失败
func IsFiatRiskCheckFail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatRiskCheckFail.String() && e.Code == 500
}

// 风险检测失败
func ErrorFiatRiskCheckFail(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatRiskCheckFail.String(), fmt.Sprintf(format, args...))
}

// ApplePay支付失败
func IsFiatApplePayPaymentFail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatApplePayPaymentFail.String() && e.Code == 500
}

// ApplePay支付失败
func ErrorFiatApplePayPaymentFail(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatApplePayPaymentFail.String(), fmt.Sprintf(format, args...))
}

// 支付渠道调用错误
func IsFiatFiathubCallError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FiatFiathubCallError.String() && e.Code == 500
}

// 支付渠道调用错误
func ErrorFiatFiathubCallError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FiatFiathubCallError.String(), fmt.Sprintf(format, args...))
}

// Admin模块错误
func IsAdminRoleNameExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminRoleNameExist.String() && e.Code == 500
}

// Admin模块错误
func ErrorAdminRoleNameExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminRoleNameExist.String(), fmt.Sprintf(format, args...))
}

// 角色不存在
func IsAdminRoleNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminRoleNotFound.String() && e.Code == 500
}

// 角色不存在
func ErrorAdminRoleNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminRoleNotFound.String(), fmt.Sprintf(format, args...))
}

// 该角色正在使用中
func IsAdminRoleInUse(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminRoleInUse.String() && e.Code == 500
}

// 该角色正在使用中
func ErrorAdminRoleInUse(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminRoleInUse.String(), fmt.Sprintf(format, args...))
}

// 邮箱已存在
func IsAdminUserEmailExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminUserEmailExist.String() && e.Code == 500
}

// 邮箱已存在
func ErrorAdminUserEmailExist(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminUserEmailExist.String(), fmt.Sprintf(format, args...))
}

// 邮箱或密码错误
func IsAdminUserEmailOrPwdError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminUserEmailOrPwdError.String() && e.Code == 500
}

// 邮箱或密码错误
func ErrorAdminUserEmailOrPwdError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminUserEmailOrPwdError.String(), fmt.Sprintf(format, args...))
}

// 用户找不到
func IsAdminUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminUserNotFound.String() && e.Code == 500
}

// 用户找不到
func ErrorAdminUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminUserNotFound.String(), fmt.Sprintf(format, args...))
}

// 旧密码错误
func IsAdminUserOldPwdError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminUserOldPwdError.String() && e.Code == 500
}

// 旧密码错误
func ErrorAdminUserOldPwdError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminUserOldPwdError.String(), fmt.Sprintf(format, args...))
}

// 管理员账号冻结
func IsAdminUserLocked(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminUserLocked.String() && e.Code == 500
}

// 管理员账号冻结
func ErrorAdminUserLocked(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminUserLocked.String(), fmt.Sprintf(format, args...))
}

// 操作不允许
func IsAdminOperationNotAllowed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdminOperationNotAllowed.String() && e.Code == 500
}

// 操作不允许
func ErrorAdminOperationNotAllowed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AdminOperationNotAllowed.String(), fmt.Sprintf(format, args...))
}
