// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.33.0
// source: wello-crypto-hub/deposit/v1/deposit.proto

package depositv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDepositServiceCreateDepositOrder = "/crypto.deposit.v1.DepositService/CreateDepositOrder"
const OperationDepositServiceGetDepositOrder = "/crypto.deposit.v1.DepositService/GetDepositOrder"

type DepositServiceHTTPServer interface {
	CreateDepositOrder(context.Context, *CreateDepositOrderRequest) (*CreateDepositOrderResponse, error)
	GetDepositOrder(context.Context, *GetDepositOrderRequest) (*GetDepositOrderResponse, error)
}

func RegisterDepositServiceHTTPServer(s *http.Server, srv DepositServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/crypto-hub/v1/deposit/create", _DepositService_CreateDepositOrder0_HTTP_Handler(srv))
	r.GET("/crypto-hub/v1/deposit/info", _DepositService_GetDepositOrder0_HTTP_Handler(srv))
}

func _DepositService_CreateDepositOrder0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDepositOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceCreateDepositOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDepositOrder(ctx, req.(*CreateDepositOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDepositOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _DepositService_GetDepositOrder0_HTTP_Handler(srv DepositServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDepositOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepositServiceGetDepositOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDepositOrder(ctx, req.(*GetDepositOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDepositOrderResponse)
		return ctx.Result(200, reply)
	}
}

type DepositServiceHTTPClient interface {
	CreateDepositOrder(ctx context.Context, req *CreateDepositOrderRequest, opts ...http.CallOption) (rsp *CreateDepositOrderResponse, err error)
	GetDepositOrder(ctx context.Context, req *GetDepositOrderRequest, opts ...http.CallOption) (rsp *GetDepositOrderResponse, err error)
}

type DepositServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDepositServiceHTTPClient(client *http.Client) DepositServiceHTTPClient {
	return &DepositServiceHTTPClientImpl{client}
}

func (c *DepositServiceHTTPClientImpl) CreateDepositOrder(ctx context.Context, in *CreateDepositOrderRequest, opts ...http.CallOption) (*CreateDepositOrderResponse, error) {
	var out CreateDepositOrderResponse
	pattern := "/crypto-hub/v1/deposit/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepositServiceCreateDepositOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DepositServiceHTTPClientImpl) GetDepositOrder(ctx context.Context, in *GetDepositOrderRequest, opts ...http.CallOption) (*GetDepositOrderResponse, error) {
	var out GetDepositOrderResponse
	pattern := "/crypto-hub/v1/deposit/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepositServiceGetDepositOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
