// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.0
// source: wello-hedging/v1/hedging.proto

package hedging

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHedgingExecute = "/hedging.v1.Hedging/Execute"
const OperationHedgingQuote = "/hedging.v1.Hedging/Quote"

type HedgingHTTPServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
}

func RegisterHedgingHTTPServer(s *http.Server, srv HedgingHTTPServer) {
	r := s.Route("/")
	r.POST("/hedging/v1/quote", _Hedging_Quote0_HTTP_Handler(srv))
	r.POST("/hedging/v1/execute", _Hedging_Execute0_HTTP_Handler(srv))
}

func _Hedging_Quote0_HTTP_Handler(srv HedgingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QuoteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHedgingQuote)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Quote(ctx, req.(*QuoteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QuoteResponse)
		return ctx.Result(200, reply)
	}
}

func _Hedging_Execute0_HTTP_Handler(srv HedgingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHedgingExecute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Execute(ctx, req.(*ExecuteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteResponse)
		return ctx.Result(200, reply)
	}
}

type HedgingHTTPClient interface {
	Execute(ctx context.Context, req *ExecuteRequest, opts ...http.CallOption) (rsp *ExecuteResponse, err error)
	Quote(ctx context.Context, req *QuoteRequest, opts ...http.CallOption) (rsp *QuoteResponse, err error)
}

type HedgingHTTPClientImpl struct {
	cc *http.Client
}

func NewHedgingHTTPClient(client *http.Client) HedgingHTTPClient {
	return &HedgingHTTPClientImpl{client}
}

func (c *HedgingHTTPClientImpl) Execute(ctx context.Context, in *ExecuteRequest, opts ...http.CallOption) (*ExecuteResponse, error) {
	var out ExecuteResponse
	pattern := "/hedging/v1/execute"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHedgingExecute))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HedgingHTTPClientImpl) Quote(ctx context.Context, in *QuoteRequest, opts ...http.CallOption) (*QuoteResponse, error) {
	var out QuoteResponse
	pattern := "/hedging/v1/quote"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHedgingQuote))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
