// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.0
// source: wello-crypto-hub/account.proto

package cryptov1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccountServiceCreateAccount = "/wello.crypto.v1.AccountService/CreateAccount"
const OperationAccountServiceGetAccount = "/wello.crypto.v1.AccountService/GetAccount"
const OperationAccountServiceListAccounts = "/wello.crypto.v1.AccountService/ListAccounts"
const OperationAccountServiceUpdateAccountStatus = "/wello.crypto.v1.AccountService/UpdateAccountStatus"

type AccountServiceHTTPServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	UpdateAccountStatus(context.Context, *UpdateAccountStatusRequest) (*Account, error)
}

func RegisterAccountServiceHTTPServer(s *http.Server, srv AccountServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/accounts", _AccountService_CreateAccount0_HTTP_Handler(srv))
	r.GET("/v1/accounts/{account_id}", _AccountService_GetAccount0_HTTP_Handler(srv))
	r.GET("/v1/accounts", _AccountService_ListAccounts0_HTTP_Handler(srv))
	r.PATCH("/v1/accounts/{account_id}/status", _AccountService_UpdateAccountStatus0_HTTP_Handler(srv))
}

func _AccountService_CreateAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAccountRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceCreateAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAccount(ctx, req.(*CreateAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAccountResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_GetAccount0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceGetAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccount(ctx, req.(*GetAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

func _AccountService_ListAccounts0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAccountsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceListAccounts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAccounts(ctx, req.(*ListAccountsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAccountsResponse)
		return ctx.Result(200, reply)
	}
}

func _AccountService_UpdateAccountStatus0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAccountStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceUpdateAccountStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAccountStatus(ctx, req.(*UpdateAccountStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Account)
		return ctx.Result(200, reply)
	}
}

type AccountServiceHTTPClient interface {
	CreateAccount(ctx context.Context, req *CreateAccountRequest, opts ...http.CallOption) (rsp *CreateAccountResponse, err error)
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...http.CallOption) (rsp *Account, err error)
	ListAccounts(ctx context.Context, req *ListAccountsRequest, opts ...http.CallOption) (rsp *ListAccountsResponse, err error)
	UpdateAccountStatus(ctx context.Context, req *UpdateAccountStatusRequest, opts ...http.CallOption) (rsp *Account, err error)
}

type AccountServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccountServiceHTTPClient(client *http.Client) AccountServiceHTTPClient {
	return &AccountServiceHTTPClientImpl{client}
}

func (c *AccountServiceHTTPClientImpl) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...http.CallOption) (*CreateAccountResponse, error) {
	var out CreateAccountResponse
	pattern := "/v1/accounts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceCreateAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/v1/accounts/{account_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceGetAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...http.CallOption) (*ListAccountsResponse, error) {
	var out ListAccountsResponse
	pattern := "/v1/accounts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAccountServiceListAccounts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AccountServiceHTTPClientImpl) UpdateAccountStatus(ctx context.Context, in *UpdateAccountStatusRequest, opts ...http.CallOption) (*Account, error) {
	var out Account
	pattern := "/v1/accounts/{account_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceUpdateAccountStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
