// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: wello-crypto-hub/metadata.proto

package cryptov1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainStatus int32

const (
	ChainStatus_CHAIN_STATUS_UNSPECIFIED ChainStatus = 0
	ChainStatus_CHAIN_STATUS_ACTIVE      ChainStatus = 1
	ChainStatus_CHAIN_STATUS_DEGRADED    ChainStatus = 2
	ChainStatus_CHAIN_STATUS_DISABLED    ChainStatus = 3
)

// Enum value maps for ChainStatus.
var (
	ChainStatus_name = map[int32]string{
		0: "CHAIN_STATUS_UNSPECIFIED",
		1: "CHAIN_STATUS_ACTIVE",
		2: "CHAIN_STATUS_DEGRADED",
		3: "CHAIN_STATUS_DISABLED",
	}
	ChainStatus_value = map[string]int32{
		"CHAIN_STATUS_UNSPECIFIED": 0,
		"CHAIN_STATUS_ACTIVE":      1,
		"CHAIN_STATUS_DEGRADED":    2,
		"CHAIN_STATUS_DISABLED":    3,
	}
)

func (x ChainStatus) Enum() *ChainStatus {
	p := new(ChainStatus)
	*p = x
	return p
}

func (x ChainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wello_crypto_hub_metadata_proto_enumTypes[0].Descriptor()
}

func (ChainStatus) Type() protoreflect.EnumType {
	return &file_wello_crypto_hub_metadata_proto_enumTypes[0]
}

func (x ChainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainStatus.Descriptor instead.
func (ChainStatus) EnumDescriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{0}
}

type ChainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NativeAsset   string                 `protobuf:"bytes,3,opt,name=native_asset,json=nativeAsset,proto3" json:"native_asset,omitempty"`
	RpcEndpoint   string                 `protobuf:"bytes,4,opt,name=rpc_endpoint,json=rpcEndpoint,proto3" json:"rpc_endpoint,omitempty"`
	Status        ChainStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=wello.crypto.v1.ChainStatus" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainInfo) Reset() {
	*x = ChainInfo{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainInfo) ProtoMessage() {}

func (x *ChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainInfo.ProtoReflect.Descriptor instead.
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ChainInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChainInfo) GetNativeAsset() string {
	if x != nil {
		return x.NativeAsset
	}
	return ""
}

func (x *ChainInfo) GetRpcEndpoint() string {
	if x != nil {
		return x.RpcEndpoint
	}
	return ""
}

func (x *ChainInfo) GetStatus() ChainStatus {
	if x != nil {
		return x.Status
	}
	return ChainStatus_CHAIN_STATUS_UNSPECIFIED
}

func (x *ChainInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChainInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Decimals      uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	IsNative      bool                   `protobuf:"varint,6,opt,name=is_native,json=isNative,proto3" json:"is_native,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *TokenInfo) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenInfo) GetIsNative() bool {
	if x != nil {
		return x.IsNative
	}
	return false
}

func (x *TokenInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	FeatureFlags  map[string]string      `protobuf:"bytes,2,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceConfig) GetFeatureFlags() map[string]string {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

func (x *ServiceConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetChainInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainInfoRequest) Reset() {
	*x = GetChainInfoRequest{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainInfoRequest) ProtoMessage() {}

func (x *GetChainInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainInfoRequest.ProtoReflect.Descriptor instead.
func (*GetChainInfoRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *GetChainInfoRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type ListChainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ChainStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=wello.crypto.v1.ChainStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsRequest) Reset() {
	*x = ListChainsRequest{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsRequest) ProtoMessage() {}

func (x *ListChainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsRequest.ProtoReflect.Descriptor instead.
func (*ListChainsRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *ListChainsRequest) GetStatus() ChainStatus {
	if x != nil {
		return x.Status
	}
	return ChainStatus_CHAIN_STATUS_UNSPECIFIED
}

type ListChainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*ChainInfo           `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsResponse) Reset() {
	*x = ListChainsResponse{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsResponse) ProtoMessage() {}

func (x *ListChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsResponse.ProtoReflect.Descriptor instead.
func (*ListChainsResponse) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ListChainsResponse) GetChains() []*ChainInfo {
	if x != nil {
		return x.Chains
	}
	return nil
}

type ListSupportedTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedTokensRequest) Reset() {
	*x = ListSupportedTokensRequest{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedTokensRequest) ProtoMessage() {}

func (x *ListSupportedTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedTokensRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedTokensRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *ListSupportedTokensRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type ListSupportedTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenInfo           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedTokensResponse) Reset() {
	*x = ListSupportedTokensResponse{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedTokensResponse) ProtoMessage() {}

func (x *ListSupportedTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedTokensResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedTokensResponse) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *ListSupportedTokensResponse) GetTokens() []*TokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetServiceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigRequest) Reset() {
	*x = GetServiceConfigRequest{}
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigRequest) ProtoMessage() {}

func (x *GetServiceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetServiceConfigRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_metadata_proto_rawDescGZIP(), []int{8}
}

var File_wello_crypto_hub_metadata_proto protoreflect.FileDescriptor

const file_wello_crypto_hub_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1fwello-crypto-hub/metadata.proto\x12\x0fwello.crypto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xf4\x02\n" +
	"\tChainInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fnative_asset\x18\x03 \x01(\tR\vnativeAsset\x12!\n" +
	"\frpc_endpoint\x18\x04 \x01(\tR\vrpcEndpoint\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.wello.crypto.v1.ChainStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.wello.crypto.v1.ChainInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x02\n" +
	"\tTokenInfo\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12\x1b\n" +
	"\tis_native\x18\x06 \x01(\bR\bisNative\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.wello.crypto.v1.TokenInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\rServiceConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12U\n" +
	"\rfeature_flags\x18\x02 \x03(\v20.wello.crypto.v1.ServiceConfig.FeatureFlagsEntryR\ffeatureFlags\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x13GetChainInfoRequest\x12\"\n" +
	"\bchain_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\achainId\"I\n" +
	"\x11ListChainsRequest\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.wello.crypto.v1.ChainStatusR\x06status\"H\n" +
	"\x12ListChainsResponse\x122\n" +
	"\x06chains\x18\x01 \x03(\v2\x1a.wello.crypto.v1.ChainInfoR\x06chains\"@\n" +
	"\x1aListSupportedTokensRequest\x12\"\n" +
	"\bchain_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\achainId\"Q\n" +
	"\x1bListSupportedTokensResponse\x122\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1a.wello.crypto.v1.TokenInfoR\x06tokens\"\x19\n" +
	"\x17GetServiceConfigRequest*z\n" +
	"\vChainStatus\x12\x1c\n" +
	"\x18CHAIN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHAIN_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15CHAIN_STATUS_DEGRADED\x10\x02\x12\x19\n" +
	"\x15CHAIN_STATUS_DISABLED\x10\x032\x80\x04\n" +
	"\x0fMetadataService\x12o\n" +
	"\fGetChainInfo\x12$.wello.crypto.v1.GetChainInfoRequest\x1a\x1a.wello.crypto.v1.ChainInfo\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/chains/{chain_id}\x12i\n" +
	"\n" +
	"ListChains\x12\".wello.crypto.v1.ListChainsRequest\x1a#.wello.crypto.v1.ListChainsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/chains\x12\x96\x01\n" +
	"\x13ListSupportedTokens\x12+.wello.crypto.v1.ListSupportedTokensRequest\x1a,.wello.crypto.v1.ListSupportedTokensResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/chains/{chain_id}/tokens\x12x\n" +
	"\x10GetServiceConfig\x12(.wello.crypto.v1.GetServiceConfigRequest\x1a\x1e.wello.crypto.v1.ServiceConfig\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/service-configBy\n" +
	"\x1edev.kratos.api.wello.crypto.v1B\rMetadataProtoP\x01ZFgithub.com/liberty-group-tech/wello-proto/wello-crypto-hub/v1;cryptov1b\x06proto3"

var (
	file_wello_crypto_hub_metadata_proto_rawDescOnce sync.Once
	file_wello_crypto_hub_metadata_proto_rawDescData []byte
)

func file_wello_crypto_hub_metadata_proto_rawDescGZIP() []byte {
	file_wello_crypto_hub_metadata_proto_rawDescOnce.Do(func() {
		file_wello_crypto_hub_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wello_crypto_hub_metadata_proto_rawDesc), len(file_wello_crypto_hub_metadata_proto_rawDesc)))
	})
	return file_wello_crypto_hub_metadata_proto_rawDescData
}

var file_wello_crypto_hub_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wello_crypto_hub_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wello_crypto_hub_metadata_proto_goTypes = []any{
	(ChainStatus)(0),                    // 0: wello.crypto.v1.ChainStatus
	(*ChainInfo)(nil),                   // 1: wello.crypto.v1.ChainInfo
	(*TokenInfo)(nil),                   // 2: wello.crypto.v1.TokenInfo
	(*ServiceConfig)(nil),               // 3: wello.crypto.v1.ServiceConfig
	(*GetChainInfoRequest)(nil),         // 4: wello.crypto.v1.GetChainInfoRequest
	(*ListChainsRequest)(nil),           // 5: wello.crypto.v1.ListChainsRequest
	(*ListChainsResponse)(nil),          // 6: wello.crypto.v1.ListChainsResponse
	(*ListSupportedTokensRequest)(nil),  // 7: wello.crypto.v1.ListSupportedTokensRequest
	(*ListSupportedTokensResponse)(nil), // 8: wello.crypto.v1.ListSupportedTokensResponse
	(*GetServiceConfigRequest)(nil),     // 9: wello.crypto.v1.GetServiceConfigRequest
	nil,                                 // 10: wello.crypto.v1.ChainInfo.MetadataEntry
	nil,                                 // 11: wello.crypto.v1.TokenInfo.MetadataEntry
	nil,                                 // 12: wello.crypto.v1.ServiceConfig.FeatureFlagsEntry
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_wello_crypto_hub_metadata_proto_depIdxs = []int32{
	0,  // 0: wello.crypto.v1.ChainInfo.status:type_name -> wello.crypto.v1.ChainStatus
	13, // 1: wello.crypto.v1.ChainInfo.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: wello.crypto.v1.ChainInfo.metadata:type_name -> wello.crypto.v1.ChainInfo.MetadataEntry
	11, // 3: wello.crypto.v1.TokenInfo.metadata:type_name -> wello.crypto.v1.TokenInfo.MetadataEntry
	12, // 4: wello.crypto.v1.ServiceConfig.feature_flags:type_name -> wello.crypto.v1.ServiceConfig.FeatureFlagsEntry
	13, // 5: wello.crypto.v1.ServiceConfig.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: wello.crypto.v1.ListChainsRequest.status:type_name -> wello.crypto.v1.ChainStatus
	1,  // 7: wello.crypto.v1.ListChainsResponse.chains:type_name -> wello.crypto.v1.ChainInfo
	2,  // 8: wello.crypto.v1.ListSupportedTokensResponse.tokens:type_name -> wello.crypto.v1.TokenInfo
	4,  // 9: wello.crypto.v1.MetadataService.GetChainInfo:input_type -> wello.crypto.v1.GetChainInfoRequest
	5,  // 10: wello.crypto.v1.MetadataService.ListChains:input_type -> wello.crypto.v1.ListChainsRequest
	7,  // 11: wello.crypto.v1.MetadataService.ListSupportedTokens:input_type -> wello.crypto.v1.ListSupportedTokensRequest
	9,  // 12: wello.crypto.v1.MetadataService.GetServiceConfig:input_type -> wello.crypto.v1.GetServiceConfigRequest
	1,  // 13: wello.crypto.v1.MetadataService.GetChainInfo:output_type -> wello.crypto.v1.ChainInfo
	6,  // 14: wello.crypto.v1.MetadataService.ListChains:output_type -> wello.crypto.v1.ListChainsResponse
	8,  // 15: wello.crypto.v1.MetadataService.ListSupportedTokens:output_type -> wello.crypto.v1.ListSupportedTokensResponse
	3,  // 16: wello.crypto.v1.MetadataService.GetServiceConfig:output_type -> wello.crypto.v1.ServiceConfig
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_wello_crypto_hub_metadata_proto_init() }
func file_wello_crypto_hub_metadata_proto_init() {
	if File_wello_crypto_hub_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wello_crypto_hub_metadata_proto_rawDesc), len(file_wello_crypto_hub_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wello_crypto_hub_metadata_proto_goTypes,
		DependencyIndexes: file_wello_crypto_hub_metadata_proto_depIdxs,
		EnumInfos:         file_wello_crypto_hub_metadata_proto_enumTypes,
		MessageInfos:      file_wello_crypto_hub_metadata_proto_msgTypes,
	}.Build()
	File_wello_crypto_hub_metadata_proto = out.File
	file_wello_crypto_hub_metadata_proto_goTypes = nil
	file_wello_crypto_hub_metadata_proto_depIdxs = nil
}
