// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: wello-crypto-hub/withdrawal.proto

package cryptov1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawalStatus int32

const (
	WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED WithdrawalStatus = 0
	WithdrawalStatus_WITHDRAWAL_STATUS_PENDING     WithdrawalStatus = 1
	WithdrawalStatus_WITHDRAWAL_STATUS_QUEUED      WithdrawalStatus = 2
	WithdrawalStatus_WITHDRAWAL_STATUS_BROADCAST   WithdrawalStatus = 3
	WithdrawalStatus_WITHDRAWAL_STATUS_CONFIRMED   WithdrawalStatus = 4
	WithdrawalStatus_WITHDRAWAL_STATUS_FAILED      WithdrawalStatus = 5
	WithdrawalStatus_WITHDRAWAL_STATUS_CANCELLED   WithdrawalStatus = 6
)

// Enum value maps for WithdrawalStatus.
var (
	WithdrawalStatus_name = map[int32]string{
		0: "WITHDRAWAL_STATUS_UNSPECIFIED",
		1: "WITHDRAWAL_STATUS_PENDING",
		2: "WITHDRAWAL_STATUS_QUEUED",
		3: "WITHDRAWAL_STATUS_BROADCAST",
		4: "WITHDRAWAL_STATUS_CONFIRMED",
		5: "WITHDRAWAL_STATUS_FAILED",
		6: "WITHDRAWAL_STATUS_CANCELLED",
	}
	WithdrawalStatus_value = map[string]int32{
		"WITHDRAWAL_STATUS_UNSPECIFIED": 0,
		"WITHDRAWAL_STATUS_PENDING":     1,
		"WITHDRAWAL_STATUS_QUEUED":      2,
		"WITHDRAWAL_STATUS_BROADCAST":   3,
		"WITHDRAWAL_STATUS_CONFIRMED":   4,
		"WITHDRAWAL_STATUS_FAILED":      5,
		"WITHDRAWAL_STATUS_CANCELLED":   6,
	}
)

func (x WithdrawalStatus) Enum() *WithdrawalStatus {
	p := new(WithdrawalStatus)
	*p = x
	return p
}

func (x WithdrawalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WithdrawalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wello_crypto_hub_withdrawal_proto_enumTypes[0].Descriptor()
}

func (WithdrawalStatus) Type() protoreflect.EnumType {
	return &file_wello_crypto_hub_withdrawal_proto_enumTypes[0]
}

func (x WithdrawalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WithdrawalStatus.Descriptor instead.
func (WithdrawalStatus) EnumDescriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{0}
}

type Withdrawal struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId       string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	AccountId          string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Chain              string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Asset              string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount             string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	DestinationAddress string                 `protobuf:"bytes,6,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Status             WithdrawalStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=wello.crypto.v1.WithdrawalStatus" json:"status,omitempty"`
	TxHash             string                 `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BroadcastAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=broadcast_at,json=broadcastAt,proto3" json:"broadcast_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{0}
}

func (x *Withdrawal) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *Withdrawal) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Withdrawal) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Withdrawal) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Withdrawal) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Withdrawal) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *Withdrawal) GetStatus() WithdrawalStatus {
	if x != nil {
		return x.Status
	}
	return WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED
}

func (x *Withdrawal) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Withdrawal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Withdrawal) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Withdrawal) GetBroadcastAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BroadcastAt
	}
	return nil
}

type CreateWithdrawalRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccountId          string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Chain              string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Asset              string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount             string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	DestinationAddress string                 `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestedBy        string                 `protobuf:"bytes,7,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateWithdrawalRequest) Reset() {
	*x = CreateWithdrawalRequest{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawalRequest) ProtoMessage() {}

func (x *CreateWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*CreateWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWithdrawalRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateWithdrawalRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type GetWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalRequest) Reset() {
	*x = GetWithdrawalRequest{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalRequest) ProtoMessage() {}

func (x *GetWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{2}
}

func (x *GetWithdrawalRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

type ListWithdrawalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Status        WithdrawalStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=wello.crypto.v1.WithdrawalStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWithdrawalsRequest) Reset() {
	*x = ListWithdrawalsRequest{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawalsRequest) ProtoMessage() {}

func (x *ListWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*ListWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{3}
}

func (x *ListWithdrawalsRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *ListWithdrawalsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListWithdrawalsRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ListWithdrawalsRequest) GetStatus() WithdrawalStatus {
	if x != nil {
		return x.Status
	}
	return WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED
}

func (x *ListWithdrawalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWithdrawalsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWithdrawalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawals   []*Withdrawal          `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWithdrawalsResponse) Reset() {
	*x = ListWithdrawalsResponse{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawalsResponse) ProtoMessage() {}

func (x *ListWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*ListWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{4}
}

func (x *ListWithdrawalsResponse) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *ListWithdrawalsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CancelWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWithdrawalRequest) Reset() {
	*x = CancelWithdrawalRequest{}
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWithdrawalRequest) ProtoMessage() {}

func (x *CancelWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wello_crypto_hub_withdrawal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*CancelWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_wello_crypto_hub_withdrawal_proto_rawDescGZIP(), []int{5}
}

func (x *CancelWithdrawalRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *CancelWithdrawalRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *CancelWithdrawalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_wello_crypto_hub_withdrawal_proto protoreflect.FileDescriptor

const file_wello_crypto_hub_withdrawal_proto_rawDesc = "" +
	"\n" +
	"!wello-crypto-hub/withdrawal.proto\x12\x0fwello.crypto.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xce\x03\n" +
	"\n" +
	"Withdrawal\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12/\n" +
	"\x13destination_address\x18\x06 \x01(\tR\x12destinationAddress\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.wello.crypto.v1.WithdrawalStatusR\x06status\x12\x17\n" +
	"\atx_hash\x18\b \x01(\tR\x06txHash\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fbroadcast_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vbroadcastAt\"\xbd\x03\n" +
	"\x17CreateWithdrawalRequest\x12'\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\taccountId\x12\x1d\n" +
	"\x05chain\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05chain\x12\x1d\n" +
	"\x05asset\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05asset\x12D\n" +
	"\x06amount\x18\x04 \x01(\tB,\xfaB)r'2%^(?:0|[1-9][0-9]*)(?:\\.[0-9]{1,18})?$R\x06amount\x128\n" +
	"\x13destination_address\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x12destinationAddress\x12R\n" +
	"\bmetadata\x18\x06 \x03(\v26.wello.crypto.v1.CreateWithdrawalRequest.MetadataEntryR\bmetadata\x12*\n" +
	"\frequested_by\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vrequestedBy\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x14GetWithdrawalRequest\x12-\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fwithdrawalId\"\xe7\x01\n" +
	"\x16ListWithdrawalsRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.wello.crypto.v1.WithdrawalStatusR\x06status\x12&\n" +
	"\tpage_size\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x80\x01\n" +
	"\x17ListWithdrawalsResponse\x12=\n" +
	"\vwithdrawals\x18\x01 \x03(\v2\x1b.wello.crypto.v1.WithdrawalR\vwithdrawals\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8c\x01\n" +
	"\x17CancelWithdrawalRequest\x12-\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fwithdrawalId\x12*\n" +
	"\fcancelled_by\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vcancelledBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*\xf3\x01\n" +
	"\x10WithdrawalStatus\x12!\n" +
	"\x1dWITHDRAWAL_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WITHDRAWAL_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18WITHDRAWAL_STATUS_QUEUED\x10\x02\x12\x1f\n" +
	"\x1bWITHDRAWAL_STATUS_BROADCAST\x10\x03\x12\x1f\n" +
	"\x1bWITHDRAWAL_STATUS_CONFIRMED\x10\x04\x12\x1c\n" +
	"\x18WITHDRAWAL_STATUS_FAILED\x10\x05\x12\x1f\n" +
	"\x1bWITHDRAWAL_STATUS_CANCELLED\x10\x062\x96\x04\n" +
	"\x11WithdrawalService\x12u\n" +
	"\x10CreateWithdrawal\x12(.wello.crypto.v1.CreateWithdrawalRequest\x1a\x1b.wello.crypto.v1.Withdrawal\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/withdrawals\x12|\n" +
	"\rGetWithdrawal\x12%.wello.crypto.v1.GetWithdrawalRequest\x1a\x1b.wello.crypto.v1.Withdrawal\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/withdrawals/{withdrawal_id}\x12}\n" +
	"\x0fListWithdrawals\x12'.wello.crypto.v1.ListWithdrawalsRequest\x1a(.wello.crypto.v1.ListWithdrawalsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/withdrawals\x12\x8c\x01\n" +
	"\x10CancelWithdrawal\x12(.wello.crypto.v1.CancelWithdrawalRequest\x1a\x1b.wello.crypto.v1.Withdrawal\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/withdrawals/{withdrawal_id}:cancelB{\n" +
	"\x1edev.kratos.api.wello.crypto.v1B\x0fWithdrawalProtoP\x01ZFgithub.com/liberty-group-tech/wello-proto/wello-crypto-hub/v1;cryptov1b\x06proto3"

var (
	file_wello_crypto_hub_withdrawal_proto_rawDescOnce sync.Once
	file_wello_crypto_hub_withdrawal_proto_rawDescData []byte
)

func file_wello_crypto_hub_withdrawal_proto_rawDescGZIP() []byte {
	file_wello_crypto_hub_withdrawal_proto_rawDescOnce.Do(func() {
		file_wello_crypto_hub_withdrawal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wello_crypto_hub_withdrawal_proto_rawDesc), len(file_wello_crypto_hub_withdrawal_proto_rawDesc)))
	})
	return file_wello_crypto_hub_withdrawal_proto_rawDescData
}

var file_wello_crypto_hub_withdrawal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wello_crypto_hub_withdrawal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wello_crypto_hub_withdrawal_proto_goTypes = []any{
	(WithdrawalStatus)(0),           // 0: wello.crypto.v1.WithdrawalStatus
	(*Withdrawal)(nil),              // 1: wello.crypto.v1.Withdrawal
	(*CreateWithdrawalRequest)(nil), // 2: wello.crypto.v1.CreateWithdrawalRequest
	(*GetWithdrawalRequest)(nil),    // 3: wello.crypto.v1.GetWithdrawalRequest
	(*ListWithdrawalsRequest)(nil),  // 4: wello.crypto.v1.ListWithdrawalsRequest
	(*ListWithdrawalsResponse)(nil), // 5: wello.crypto.v1.ListWithdrawalsResponse
	(*CancelWithdrawalRequest)(nil), // 6: wello.crypto.v1.CancelWithdrawalRequest
	nil,                             // 7: wello.crypto.v1.CreateWithdrawalRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_wello_crypto_hub_withdrawal_proto_depIdxs = []int32{
	0,  // 0: wello.crypto.v1.Withdrawal.status:type_name -> wello.crypto.v1.WithdrawalStatus
	8,  // 1: wello.crypto.v1.Withdrawal.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: wello.crypto.v1.Withdrawal.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 3: wello.crypto.v1.Withdrawal.broadcast_at:type_name -> google.protobuf.Timestamp
	7,  // 4: wello.crypto.v1.CreateWithdrawalRequest.metadata:type_name -> wello.crypto.v1.CreateWithdrawalRequest.MetadataEntry
	0,  // 5: wello.crypto.v1.ListWithdrawalsRequest.status:type_name -> wello.crypto.v1.WithdrawalStatus
	1,  // 6: wello.crypto.v1.ListWithdrawalsResponse.withdrawals:type_name -> wello.crypto.v1.Withdrawal
	2,  // 7: wello.crypto.v1.WithdrawalService.CreateWithdrawal:input_type -> wello.crypto.v1.CreateWithdrawalRequest
	3,  // 8: wello.crypto.v1.WithdrawalService.GetWithdrawal:input_type -> wello.crypto.v1.GetWithdrawalRequest
	4,  // 9: wello.crypto.v1.WithdrawalService.ListWithdrawals:input_type -> wello.crypto.v1.ListWithdrawalsRequest
	6,  // 10: wello.crypto.v1.WithdrawalService.CancelWithdrawal:input_type -> wello.crypto.v1.CancelWithdrawalRequest
	1,  // 11: wello.crypto.v1.WithdrawalService.CreateWithdrawal:output_type -> wello.crypto.v1.Withdrawal
	1,  // 12: wello.crypto.v1.WithdrawalService.GetWithdrawal:output_type -> wello.crypto.v1.Withdrawal
	5,  // 13: wello.crypto.v1.WithdrawalService.ListWithdrawals:output_type -> wello.crypto.v1.ListWithdrawalsResponse
	1,  // 14: wello.crypto.v1.WithdrawalService.CancelWithdrawal:output_type -> wello.crypto.v1.Withdrawal
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wello_crypto_hub_withdrawal_proto_init() }
func file_wello_crypto_hub_withdrawal_proto_init() {
	if File_wello_crypto_hub_withdrawal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wello_crypto_hub_withdrawal_proto_rawDesc), len(file_wello_crypto_hub_withdrawal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wello_crypto_hub_withdrawal_proto_goTypes,
		DependencyIndexes: file_wello_crypto_hub_withdrawal_proto_depIdxs,
		EnumInfos:         file_wello_crypto_hub_withdrawal_proto_enumTypes,
		MessageInfos:      file_wello_crypto_hub_withdrawal_proto_msgTypes,
	}.Build()
	File_wello_crypto_hub_withdrawal_proto = out.File
	file_wello_crypto_hub_withdrawal_proto_goTypes = nil
	file_wello_crypto_hub_withdrawal_proto_depIdxs = nil
}
