// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: wello-crypto-hub/withdrawal.proto

package cryptov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _withdrawal_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Withdrawal with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Withdrawal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Withdrawal with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WithdrawalMultiError, or
// nil if none found.
func (m *Withdrawal) ValidateAll() error {
	return m.validate(true)
}

func (m *Withdrawal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WithdrawalId

	// no validation rules for AccountId

	// no validation rules for Chain

	// no validation rules for Asset

	// no validation rules for Amount

	// no validation rules for DestinationAddress

	// no validation rules for Status

	// no validation rules for TxHash

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBroadcastAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "BroadcastAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "BroadcastAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBroadcastAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "BroadcastAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WithdrawalMultiError(errors)
	}

	return nil
}

// WithdrawalMultiError is an error wrapping multiple validation errors
// returned by Withdrawal.ValidateAll() if the designated constraints aren't met.
type WithdrawalMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawalMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawalMultiError) AllErrors() []error { return m }

// WithdrawalValidationError is the validation error returned by
// Withdrawal.Validate if the designated constraints aren't met.
type WithdrawalValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawalValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawalValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawalValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawalValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawalValidationError) ErrorName() string { return "WithdrawalValidationError" }

// Error satisfies the builtin error interface
func (e WithdrawalValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawalValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawalValidationError{}

// Validate checks the field values on CreateWithdrawalRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWithdrawalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWithdrawalRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWithdrawalRequestMultiError, or nil if none found.
func (m *CreateWithdrawalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWithdrawalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetAccountId()); err != nil {
		err = CreateWithdrawalRequestValidationError{
			field:  "AccountId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetChain()) < 1 {
		err := CreateWithdrawalRequestValidationError{
			field:  "Chain",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAsset()) < 1 {
		err := CreateWithdrawalRequestValidationError{
			field:  "Asset",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateWithdrawalRequest_Amount_Pattern.MatchString(m.GetAmount()) {
		err := CreateWithdrawalRequestValidationError{
			field:  "Amount",
			reason: "value does not match regex pattern \"^(?:0|[1-9][0-9]*)(?:\\\\.[0-9]{1,18})?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDestinationAddress()) < 1 {
		err := CreateWithdrawalRequestValidationError{
			field:  "DestinationAddress",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Metadata

	if utf8.RuneCountInString(m.GetRequestedBy()) < 1 {
		err := CreateWithdrawalRequestValidationError{
			field:  "RequestedBy",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateWithdrawalRequestMultiError(errors)
	}

	return nil
}

func (m *CreateWithdrawalRequest) _validateUuid(uuid string) error {
	if matched := _withdrawal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateWithdrawalRequestMultiError is an error wrapping multiple validation
// errors returned by CreateWithdrawalRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateWithdrawalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWithdrawalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWithdrawalRequestMultiError) AllErrors() []error { return m }

// CreateWithdrawalRequestValidationError is the validation error returned by
// CreateWithdrawalRequest.Validate if the designated constraints aren't met.
type CreateWithdrawalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWithdrawalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWithdrawalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWithdrawalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWithdrawalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWithdrawalRequestValidationError) ErrorName() string {
	return "CreateWithdrawalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWithdrawalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWithdrawalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWithdrawalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWithdrawalRequestValidationError{}

var _CreateWithdrawalRequest_Amount_Pattern = regexp.MustCompile("^(?:0|[1-9][0-9]*)(?:\\.[0-9]{1,18})?$")

// Validate checks the field values on GetWithdrawalRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWithdrawalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWithdrawalRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWithdrawalRequestMultiError, or nil if none found.
func (m *GetWithdrawalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWithdrawalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetWithdrawalId()); err != nil {
		err = GetWithdrawalRequestValidationError{
			field:  "WithdrawalId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetWithdrawalRequestMultiError(errors)
	}

	return nil
}

func (m *GetWithdrawalRequest) _validateUuid(uuid string) error {
	if matched := _withdrawal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetWithdrawalRequestMultiError is an error wrapping multiple validation
// errors returned by GetWithdrawalRequest.ValidateAll() if the designated
// constraints aren't met.
type GetWithdrawalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWithdrawalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWithdrawalRequestMultiError) AllErrors() []error { return m }

// GetWithdrawalRequestValidationError is the validation error returned by
// GetWithdrawalRequest.Validate if the designated constraints aren't met.
type GetWithdrawalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWithdrawalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWithdrawalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWithdrawalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWithdrawalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWithdrawalRequestValidationError) ErrorName() string {
	return "GetWithdrawalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetWithdrawalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWithdrawalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWithdrawalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWithdrawalRequestValidationError{}

// Validate checks the field values on ListWithdrawalsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWithdrawalsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWithdrawalsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWithdrawalsRequestMultiError, or nil if none found.
func (m *ListWithdrawalsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWithdrawalsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Chain

	// no validation rules for Asset

	// no validation rules for Status

	if val := m.GetPageSize(); val < 1 || val > 100 {
		err := ListWithdrawalsRequestValidationError{
			field:  "PageSize",
			reason: "value must be inside range [1, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListWithdrawalsRequestMultiError(errors)
	}

	return nil
}

// ListWithdrawalsRequestMultiError is an error wrapping multiple validation
// errors returned by ListWithdrawalsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListWithdrawalsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWithdrawalsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWithdrawalsRequestMultiError) AllErrors() []error { return m }

// ListWithdrawalsRequestValidationError is the validation error returned by
// ListWithdrawalsRequest.Validate if the designated constraints aren't met.
type ListWithdrawalsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWithdrawalsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWithdrawalsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWithdrawalsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWithdrawalsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWithdrawalsRequestValidationError) ErrorName() string {
	return "ListWithdrawalsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListWithdrawalsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWithdrawalsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWithdrawalsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWithdrawalsRequestValidationError{}

// Validate checks the field values on ListWithdrawalsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWithdrawalsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWithdrawalsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWithdrawalsResponseMultiError, or nil if none found.
func (m *ListWithdrawalsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWithdrawalsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetWithdrawals() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListWithdrawalsResponseValidationError{
						field:  fmt.Sprintf("Withdrawals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListWithdrawalsResponseValidationError{
						field:  fmt.Sprintf("Withdrawals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListWithdrawalsResponseValidationError{
					field:  fmt.Sprintf("Withdrawals[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListWithdrawalsResponseMultiError(errors)
	}

	return nil
}

// ListWithdrawalsResponseMultiError is an error wrapping multiple validation
// errors returned by ListWithdrawalsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListWithdrawalsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWithdrawalsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWithdrawalsResponseMultiError) AllErrors() []error { return m }

// ListWithdrawalsResponseValidationError is the validation error returned by
// ListWithdrawalsResponse.Validate if the designated constraints aren't met.
type ListWithdrawalsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWithdrawalsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWithdrawalsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWithdrawalsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWithdrawalsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWithdrawalsResponseValidationError) ErrorName() string {
	return "ListWithdrawalsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListWithdrawalsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWithdrawalsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWithdrawalsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWithdrawalsResponseValidationError{}

// Validate checks the field values on CancelWithdrawalRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelWithdrawalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelWithdrawalRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelWithdrawalRequestMultiError, or nil if none found.
func (m *CancelWithdrawalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelWithdrawalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetWithdrawalId()); err != nil {
		err = CancelWithdrawalRequestValidationError{
			field:  "WithdrawalId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCancelledBy()) < 1 {
		err := CancelWithdrawalRequestValidationError{
			field:  "CancelledBy",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return CancelWithdrawalRequestMultiError(errors)
	}

	return nil
}

func (m *CancelWithdrawalRequest) _validateUuid(uuid string) error {
	if matched := _withdrawal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CancelWithdrawalRequestMultiError is an error wrapping multiple validation
// errors returned by CancelWithdrawalRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelWithdrawalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelWithdrawalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelWithdrawalRequestMultiError) AllErrors() []error { return m }

// CancelWithdrawalRequestValidationError is the validation error returned by
// CancelWithdrawalRequest.Validate if the designated constraints aren't met.
type CancelWithdrawalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelWithdrawalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelWithdrawalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelWithdrawalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelWithdrawalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelWithdrawalRequestValidationError) ErrorName() string {
	return "CancelWithdrawalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelWithdrawalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelWithdrawalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelWithdrawalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelWithdrawalRequestValidationError{}
